# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /employees_post for http method type POST 
# RoostTestHash=e5b9d8d67f
# 
# 

# ********RoostGPT********
Feature: Add Employee

  Background:
    * def baseURL = karate.properties['EMPLOYEE_SERVICE_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Add Employee with valid input
    Given path '/employees'
    And request
    """
    {
      "id": '<id>',
      "jobTitle": '<jobTitle>',
      "name": '<name>',
      "email": '<email>'
    }
    """
    When method POST
    Then status <statusCode>
    And match response ==
    """
    {
      "id": '##string',
      "jobTitle": '##string',
      "name": '##string',
      "email": '##string'
    }
    """
    Examples:
      | id                                  | jobTitle       | name       | email                    | statusCode |
      | 'd290f1ee-6c54-4b01-90e6-d701748f0851' | 'System Analyst' | 'John Smith' | 'john.smith@acme-corp.com' | 201        |
      | 'd290f1ee-6c54-4b01-90e6-d701748f0852' | 'System Analyst' | 'Jane Doe'  | 'jane.doe@acme-corp.com'  | 201        |

  Scenario Outline: Add Employee with invalid input
    Given path '/employees'
    And request
    """
    {
      "id": '<id>',
      "jobTitle": '<jobTitle>',
      "name": '<name>',
      "email": '<email>'
    }
    """
    When method POST
    Then status <statusCode>
    And match response.error ==
    """
    {
      "code": '##number',
      "message": '##string'
    }
    """
    Examples:
      | id                                  | jobTitle       | name       | email                    | statusCode |
      | 'd290f1ee-6c54-4b01-90e6-d701748f0851' | ''             | 'John Smith' | 'john.smith@acme-corp.com' | 400        |
      | 'd290f1ee-6c54-4b01-90e6-d701748f0852' | 'System Analyst' | ''          | 'jane.doe@acme-corp.com'  | 400        |

  Scenario Outline: Add Employee with existing employee
    Given path '/employees'
    And request
    """
    {
      "id": '<id>',
      "jobTitle": '<jobTitle>',
      "name": '<name>',
      "email": '<email>'
    }
    """
    When method POST
    Then status <statusCode>
    And match response.error ==
    """
    {
      "code": '##number',
      "message": '##string'
    }
    """
    Examples:
      | id                                  | jobTitle       | name       | email                    | statusCode |
      | 'd290f1ee-6c54-4b01-90e6-d701748f0851' | 'System Analyst' | 'John Smith' | 'john.smith@acme-corp.com' | 409        |
