# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=0a005b8a0e
# 
# 

# ********RoostGPT********
Feature: Get Employee by ID

  Background:
    * def baseURL = karate.properties['EMPLOYEE_SERVICE_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Get Employee by ID - Valid ID
    Given path '/employees', '/<id>'
    When method get
    Then status 200
    And match response.id == '#string'
    And match response.jobTitle == '#string'
    And match response.name == '#string'
    And match response.email == '#string'
    Examples:
      | id                                   |
      | 'd290f1ee-6c54-4b01-90e6-d701748f0851' |

  Scenario Outline: Get Employee by ID - Invalid ID
    Given path '/employees', '/<id>'
    When method get
    Then status 404
    Examples:
      | id                                   |
      | 'invalid-uuid'                      |
