# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /employees_get for http method type GET 
# RoostTestHash=48e4dd6cd8
# 
# 

# ********RoostGPT********
Feature: Search Employees

  Background:
    * def baseURL = karate.properties['EMPLOYEE_SERVICE_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Search Employees with valid query parameters
    Given path '/employees'
    And param searchString = '<searchString>'
    When method get
    Then status <statusCode>
    And match response == '#array'
    And match each response[*].id == '#? _ == null || typeof _ == "string"'
    And match each response[*].jobTitle == '#string'
    And match each response[*].name == '#string'
    And match each response[*].email == '#string'

    Examples:
      | searchString      | statusCode |
      | 'System Analyst'  | 200         |
      | 'John Smith'     | 200         |
      | 'john.smith@acme-corp.com' | 200   |
      | 'invalid'        | 400         |

  Scenario: Search Employees without query parameters
    Given path '/employees'
    When method get
    Then status 200
    And match response == '#array'
    And match each response[*].id == '#? _ == null || typeof _ == "string"'
    And match each response[*].jobTitle == '#string'
    And match each response[*].name == '#string'
    And match each response[*].email == '#string'
