# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/auditlogs/{account}/actions_get for http method type GET 
# RoostTestHash=ee4cf11a36
# 
# 

# ********RoostGPT********
Feature: List audit log actions

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: List audit log actions for a valid account
    Given path '/v2/auditlogs', account, '/actions'
    When method get
    Then status 200
    And match response ==
    """
    {
      actions: {
        org: {
          actions: [
            {
              name: '#string',
              description: '#string',
              label: '#string'
            }
          ],
          label: '#string'
        },
        repo: {
          actions: [
            {
              name: '#string',
              description: '#string',
              label: '#string'
            }
          ],
          label: '#string'
        }
      }
    }
    """
    And match response.actions == '#object'
    And match response.actions.org == '#object'
    And match response.actions.org.actions == '#array'
    And match each response.actions.org.actions[*].name == '#string'
    And match each response.actions.org.actions[*].description == '#string'
    And match each response.actions.org.actions[*].label == '#string'
    And match response.actions.org.label == '#string'
    And match response.actions.repo == '#object'
    And match response.actions.repo.actions == '#array'
    And match each response.actions.repo.actions[*].name == '#string'
    And match each response.actions.repo.actions[*].description == '#string'
    And match each response.actions.repo.actions[*].label == '#string'
    And match response.actions.repo.label == '#string'

    Examples:
    | account |
    | 'org'   |
    | 'repo'  |

Scenario: List audit log actions for an invalid account
    Given path '/v2/auditlogs', 'invalid_account', '/actions'
    When method get
    Then status 429
    And match response ==
    """
    {
      detail: 'Rate limit exceeded',
      error: false
    }
    """
    And match response.detail == 'Rate limit exceeded'
    And match response.error == false

Scenario: List audit log actions with server error
    Given path '/v2/auditlogs', 'org', '/actions'
    When method get
    Then status 500

Scenario: List audit log actions with unexpected error
    Given path '/v2/auditlogs', 'org', '/actions'
    When method get
    Then status 500
    And match response ==
    """
    {
      code: '#number',
      message: '#string',
      details: [
        {
          type_url: '#string',
          value: '#string'
        }
      ]
    }
    """
    And match response.code == '#number'
    And match response.message == '#string'
    And match response.details == '#array'
    And match each response.details[*].type_url == '#string'
    And match each response.details[*].value == '#string'
