# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/access-tokens/{uuid}_patch for http method type PATCH 
# RoostTestHash=7088c9c360
# 
# 

# ********RoostGPT********
Feature: Update Personal Access Token

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Update personal access token with valid input
    Given path '/v2/access-tokens/<uuid>'
    And request
    """
    {
      "token_label": '<token_label>',
      "is_active": <is_active>
    }
    """
    When method put
    Then status 200
    And match response ==
    """
    {
      "uuid": '#string',
      "client_id": '#string',
      "creator_ip": '#string',
      "creator_ua": '#string',
      "created_at": '#string',
      "last_used": '##null || string',
      "generated_by": '#string',
      "is_active": '#boolean',
      "token": '#string',
      "token_label": '#string',
      "scopes": '#array'
    }
    """
    Examples:
      | uuid                                 | token_label          | is_active |
      | 'b30bbf97-506c-4ecd-aabc-842f3cb484fb' | 'My read only token'  | true      |
      | 'b30bbf97-506c-4ecd-aabc-842f3cb484fb' | 'My read only token'  | false     |

  Scenario Outline: Update personal access token with invalid input
    Given path '/v2/access-tokens/<uuid>'
    And request
    """
    {
      "token_label": '<token_label>',
      "is_active": <is_active>
    }
    """
    When method put
    Then status 400
    And match response ==
    """
    {
      "fields": '#object',
      "text": '#string'
    }
    """
    Examples:
      | uuid                                 | token_label          | is_active |
      | 'b30bbf97-506c-4ecd-aabc-842f3cb484fb' | 'My read only token'  | 'invalid' |
      | 'b30bbf97-506c-4ecd-aabc-842f3cb484fb' | ''                    | true      |

  Scenario: Update personal access token with missing authorization
    Given path '/v2/access-tokens/b30bbf97-506c-4ecd-aabc-842f3cb484fb'
    And request
    """
    {
      "token_label": 'My read only token',
      "is_active": true
    }
    """
    When method put
    Then status 401
    And match response ==
    """
    {
      "detail": '#string',
      "message": '#string'
    }
    """
