# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/auditlogs/{account}_get for http method type GET 
# RoostTestHash=a6b89a276b
# 
# 

# ********RoostGPT********
Feature: List audit log events

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json', Authorization: '#(Bearer + karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN'])' }

Scenario Outline: List audit log events for a given namespace
    * def account = <account>
    * def action = <action>
    * def name = <name>
    * def actor = <actor>
    * def from = <from>
    * def to = <to>
    * def page = <page>
    * def page_size = <page_size>

    Given path '/v2/auditlogs/' + account
    And param action = action
    And param name = name
    And param actor = actor
    And param from = from
    And param to = to
    And param page = page
    And param page_size = page_size
    When method get
    Then status 200
    And match response ==
    """
    {
        logs: [
            {
                account: '#string',
                action: '#string',
                name: '#string',
                actor: '#string',
                data: '#object',
                timestamp: '#string',
                action_description: '#string'
            }
        ]
    }
    """
    And match response.logs[*].account == '#string'
    And match response.logs[*].action == '#string'
    And match response.logs[*].name == '#string'
    And match response.logs[*].actor == '#string'
    And match response.logs[*].data == '#object'
    And match response.logs[*].timestamp == '#string'
    And match response.logs[*].action_description == '#string'

    Examples:
    | account | action           | name          | actor    | from                     | to                       | page | page_size |
    | 'docker'| 'repo.tag.push'  | 'docker/example' | 'docker' | '2021-02-19T01:34:35Z' | '2021-02-19T01:34:35Z' | 1    | 25        |

Scenario: List audit log events for a given namespace with invalid account
    * def account = 'invalid_account'
    Given path '/v2/auditlogs/' + account
    When method get
    Then status 429
    And match response ==
    """
    {
        detail: '#string',
        error: false
    }
    """
    And match response.detail == '#string'
    And match response.error == false

Scenario: List audit log events for a given namespace with server error
    * def account = 'docker'
    Given path '/v2/auditlogs/' + account
    When method get
    Then status 500
    And match response == '#object'

Scenario: List audit log events for a given namespace with unexpected error
    * def account = 'docker'
    Given path '/v2/auditlogs/' + account
    When method get
    Then status 500
    And match response ==
    """
    {
        code: '#number',
        message: '#string',
        details: [
            {
                type_url: '#string',
                value: '#string'
            }
        ]
    }
    """
    And match response.code == '#number'
    And match response.message == '#string'
    And match response.details[*].type_url == '#string'
    And match response.details[*].value == '#string'
