# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/access-tokens/{uuid}_get for http method type GET 
# RoostTestHash=562b2d0e70
# 
# 

# ********RoostGPT********
Feature: Get personal access token

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Get personal access token with valid UUID
    Given path '/v2/access-tokens', <uuid>
    When method get
    Then status 200
    And match response ==
    """
    {
        uuid: '#string',
        client_id: '#string',
        creator_ip: '#string',
        creator_ua: '#string',
        created_at: '#string',
        last_used: '#? _ == null || typeof _ == "string"',
        generated_by: '#string',
        is_active: '#boolean',
        token: '#string',
        token_label: '#string',
        scopes: '#[] string'
    }
    """
    Examples:
    | uuid                              |
    | 'b30bbf97-506c-4ecd-aabc-842f3cb484fb' |

Scenario: Get personal access token with invalid UUID
    Given path '/v2/access-tokens', 'invalid-uuid'
    When method get
    Then status 404
    And match response ==
    """
    {
        detail: '#string',
        message: '#string'
    }
    """

Scenario: Get personal access token with unauthorized access
    Given path '/v2/access-tokens', 'b30bbf97-506c-4ecd-aabc-842f3cb484fb'
    And configure headers = { Authorization: 'Bearer invalid-token', Accept: 'application/json' }
    When method get
    Then status 401
    And match response ==
    """
    {
        detail: '#string',
        message: '#string'
    }
    """
