# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/auth/token_post for http method type POST 
# RoostTestHash=60edbd5d60
# 
# 

# ********RoostGPT********
Feature: Create access token

Background:
	* def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
	* url baseURL
	* configure headers = { Accept: 'application/json' }

Scenario Outline: Successful token creation
	Given path '/v2/auth/token'
	And request
	"""
	{
		"identifier": '<identifier>',
		"secret": '<secret>'
	}
	"""
	When method POST
	Then status 200
	And match response.access_token == '#string'
	Examples:
		| identifier  | secret                   |
		| 'myusername'| 'dckr_pat_124509ugsdjga93'|

Scenario Outline: Authentication failed
	Given path '/v2/auth/token'
	And request
	"""
	{
		"identifier": '<identifier>',
		"secret": '<secret>'
	}
	"""
	When method POST
	Then status 401
	And match response.errinfo == '##object'
	And match response.detail == '##string'
	And match response.message == '##string'
	Examples:
		| identifier  | secret                   |
		| 'wronguser' | 'wrongpassword'          |
