# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/access-tokens_post for http method type POST 
# RoostTestHash=1b354e13b3
# 
# 

# ********RoostGPT********
Feature: Create personal access token

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Create personal access token with valid input
    * request
    """
    {
        "token_label": '<token_label>',
        "scopes": <scopes>,
        "expires_at": '<expires_at>'
    }
    """
    * method post
    * path '/v2/access-tokens'
    * status 201
    * match response.uuid == '#string'
    * match response.client_id == '#string'
    * match response.creator_ip == '#string'
    * match response.creator_ua == '#string'
    * match response.created_at == '#string'
    * match response.last_used == '#? _ == null || typeof _ == "string"'
    * match response.generated_by == '#string'
    * match response.is_active == '#boolean'
    * match response.token == '#string'
    * match response.token_label == '#string'
    * match response.scopes == '#array'
    * match each response.scopes[*].scopes == '#string'

    Examples:
    | token_label           | scopes                      | expires_at                         |
    | 'My read only token' | ['repo:read']               | '2021-10-28T18:30:19.520861Z'    |
    | 'My write token'     | ['repo:write']              | '2021-10-28T18:30:19.520861Z'    |
    | 'My admin token'    | ['repo:admin']              | '2021-10-28T18:30:19.520861Z'    |
    | 'My public read token' | ['repo:public_read']      | '2021-10-28T18:30:19.520861Z'    |

Scenario Outline: Create personal access token with invalid input
    * request
    """
    {
        "token_label": '<token_label>',
        "scopes": <scopes>,
        "expires_at": '<expires_at>'
    }
    """
    * method post
    * path '/v2/access-tokens'
    * status 400
    * match response.fields == '#object'
    * match response.text == '#string'

    Examples:
    | token_label           | scopes                      | expires_at                         |
    | ''                   | ['repo:read']               | '2021-10-28T18:30:19.520861Z'    |
    | 'My read only token' | []                          | '2021-10-28T18:30:19.520861Z'    |
    | 'My read only token' | ['invalid_scope']           | '2021-10-28T18:30:19.520861Z'    |

Scenario: Create personal access token without authorization
    * request
    """
    {
        "token_label": 'My read only token',
        "scopes": ['repo:read'],
        "expires_at": '2021-10-28T18:30:19.520861Z'
    }
    """
    * method post
    * path '/v2/access-tokens'
    * status 401
    * match response.detail == '#string'
    * match response.message == '#string'
