# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/access-tokens_get for http method type GET 
# RoostTestHash=91d0ccab9d
# 
# 

# ********RoostGPT********
Feature: List personal access tokens

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: List personal access tokens with valid query parameters
    Given path '/v2/access-tokens'
    And param page = <page>
    And param page_size = <page_size>
    When method get
    Then status 200
    And match response == """
    {
        count: '#number',
        next: '#? _ == null || typeof _ == "string"',
        previous: '#? _ == null || typeof _ == "string"',
        active_count: '#number',
        results: '#[]'
    }
    """
    And match each results[*].uuid == '#string'
    And match each results[*].client_id == '#string'
    And match each results[*].creator_ip == '#string'
    And match each results[*].creator_ua == '#string'
    And match each results[*].created_at == '#string'
    And match each results[*].last_used == '#? _ == null || typeof _ == "string"'
    And match each results[*].generated_by == '#string'
    And match each results[*].is_active == '#boolean'
    And match each results[*].token == '#string'
    And match each results[*].token_label == '#string'
    And match each results[*].scopes == '#[]'

    Examples:
    | page | page_size |
    | 1    | 10        |
    | 2    | 20        |

Scenario: List personal access tokens with invalid query parameters
    Given path '/v2/access-tokens'
    And param page = 'invalid'
    And param page_size = 'invalid'
    When method get
    Then status 400
    And match response == """
    {
        fields: '#object',
        text: '#string'
    }
    """

Scenario: List personal access tokens with missing authorization
    Given path '/v2/access-tokens'
    And configure headers = { Accept: 'application/json' }
    When method get
    Then status 401
    And match response == """
    {
        detail: '#string',
        message: '#string'
    }
    """
