# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/access-tokens/{uuid}_delete for http method type DELETE 
# RoostTestHash=487058a011
# 
# 

# ********RoostGPT********
Feature: Delete personal access token

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }

Scenario Outline: Delete personal access token with valid UUID
    Given path '/v2/access-tokens/<uuid>'
    When method delete
    Then status <expectedStatusCode>
    * def responseBody = response
    * if (responseStatus == 204) {
        Then match responseBody == '#null'
      } else if (responseStatus == 401) {
        Then match responseBody.detail == '##string'
        And match responseBody.message == '##string'
      } else if (responseStatus == 404) {
        Then match responseBody.detail == '##string'
        And match responseBody.message == '##string'
      }

    Examples:
    | uuid                | expectedStatusCode |
    | 'valid-uuid-12345'  | 204                |
    | 'invalid-uuid-67890'| 404                |
    | 'unauthorized-uuid' | 401                |
