# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/invites/{id}/resend_patch for http method type PATCH 
# RoostTestHash=f8458ecc0a
# 
# 

# ********RoostGPT********
Feature: Resend an invite

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Resend an invite with valid input
    Given path '/v2/invites/<id>/resend'
    When method POST
    Then status <status>
    And match response == '##null'

    Examples:
      | id   | status |
      | 123  | 204    |
      | 456  | 401    |
      | 789  | 403    |
      | 101  | 404    |

  Scenario: Resend an invite with invalid input
    Given path '/v2/invites/invalid_id/resend'
    When method POST
    Then status 404
    And match response.errinfo == '##object'
    And match response.detail == '##string'
    And match response.message == '##string'

  Scenario: Resend an invite with missing authorization
    Given path '/v2/invites/123/resend'
    And configure headers = { Accept: 'application/json' }
    When method POST
    Then status 401
    And match response.errinfo == '##object'
    And match response.detail == '##string'
    And match response.message == '##string'

  Scenario: Resend an invite with forbidden access
    Given path '/v2/invites/123/resend'
    And configure headers = { Authorization: 'Bearer invalid_token', Accept: 'application/json' }
    When method POST
    Then status 403
    And match response.errinfo == '##object'
    And match response.detail == '##string'
    And match response.message == '##string'
