# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/invites/{id}_delete for http method type DELETE 
# RoostTestHash=914c5fa8ae
# 
# 

# ********RoostGPT********
Feature: Cancel an invite

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Cancel an invite with valid ID
    Given path '/v2/invites/<id>'
    When method DELETE
    Then status 204
    And match response == null

    Examples:
      | id         |
      | '123456'   |
      | '789012'   |

  Scenario: Cancel an invite with invalid ID
    Given path '/v2/invites/abcdef'
    When method DELETE
    Then status 404
    And match response.errinfo == '##object'
    And match response.detail == '##string'
    And match response.message == '##string'

  Scenario: Cancel an invite with unauthorized access
    Given path '/v2/invites/123456'
    * configure headers = { Authorization: 'Bearer invalid_token', Accept: 'application/json' }
    When method DELETE
    Then status 401
    And match response.errinfo == '##object'
    And match response.detail == '##string'
    And match response.message == '##string'

  Scenario: Cancel an invite with forbidden access
    Given path '/v2/invites/123456'
    * configure headers = { Authorization: 'Bearer forbidden_token', Accept: 'application/json' }
    When method DELETE
    Then status 403
    And match response.errinfo == '##object'
    And match response.detail == '##string'
    And match response.message == '##string'
