# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/invites/bulk_post for http method type POST 
# RoostTestHash=1ffd80a053
# 
# 

# ********RoostGPT********
Feature: Bulk create invites

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Bulk create invites with valid input
    Given path '/v2/invites/bulk'
    And request
    """
    {
        "org": '<org>',
        "team": '<team>',
        "role": '<role>',
        "invitees": <invitees>,
        "dry_run": <dry_run>
    }
    """
    When method POST
    Then status 202
    And match response.invitees.invitees[*].invitee == '##string'
    And match response.invitees.invitees[*].status == '##string'
    And match response.invitees.invitees[*].invite == '#? _ == null || typeof _ == "object"'
    And match response.invitees.invitees[*].invite.id == '##string'
    And match response.invitees.invitees[*].invite.inviter_username == '##string'
    And match response.invitees.invitees[*].invite.invitee == '##string'
    And match response.invitees.invitees[*].invite.org == '##string'
    And match response.invitees.invitees[*].invite.team == '##string'
    And match response.invitees.invitees[*].invite.created_at == '##string'

    Examples:
    | org    | team   | role   | invitees                                                                 | dry_run |
    | 'docker' | 'owners' | 'member' | ['invitee1DockerId', 'invitee2@docker.com', 'invitee3@docker.com'] | true    |

Scenario Outline: Bulk create invites with missing required fields
    Given path '/v2/invites/bulk'
    And request
    """
    {
        "org": '<org>',
        "team": '<team>',
        "role": '<role>',
        "invitees": <invitees>,
        "dry_run": <dry_run>
    }
    """
    When method POST
    Then status 400
    And match response.errinfo == '##object'
    And match response.detail == '##string'
    And match response.message == '##string'

    Examples:
    | org    | team   | role   | invitees                                                                 | dry_run |
    | 'docker' | 'owners' | 'member' | ['invitee1DockerId', 'invitee2@docker.com', 'invitee3@docker.com'] | null    |
    | null    | 'owners' | 'member' | ['invitee1DockerId', 'invitee2@docker.com', 'invitee3@docker.com'] | true    |
    | 'docker' | null   | 'member' | ['invitee1DockerId', 'invitee2@docker.com', 'invitee3@docker.com'] | true    |
    | 'docker' | 'owners' | null   | ['invitee1DockerId', 'invitee2@docker.com', 'invitee3@docker.com'] | true    |
    | 'docker' | 'owners' | 'member' | null                                                                 | true    |

Scenario: Bulk create invites with unauthorized access
    Given path '/v2/invites/bulk'
    And request
    """
    {
        "org": 'docker',
        "team": 'owners',
        "role": 'member',
        "invitees": ['invitee1DockerId', 'invitee2@docker.com', 'invitee3@docker.com'],
        "dry_run": true
    }
    """
    When method POST
    Then status 401
    And match response.errinfo == '##object'
    And match response.detail == '##string'
    And match response.message == '##string'

Scenario: Bulk create invites with conflict
    Given path '/v2/invites/bulk'
    And request
    """
    {
        "org": 'docker',
        "team": 'owners',
        "role": 'member',
        "invitees": ['invitee1DockerId', 'invitee2@docker.com', 'invitee3@docker.com'],
        "dry_run": true
    }
    """
    When method POST
    Then status 409
    And match response.errinfo == '##object'
    And match response.detail == '##string'
    And match response.message == '##string'
