# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/namespaces/{namespace}/repositories/{repository}/tags_get for http method type GET 
# RoostTestHash=cf072beb53
# 
# 

# ********RoostGPT********
Feature: List repository tags

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: List repository tags with valid parameters
    Given path '/v2/namespaces/<namespace>/repositories/<repository>/tags'
    And param page = <page>
    And param page_size = <page_size>
    When method get
    Then status <status>
    And match response ==
      """
      {
          count: '#number',
          next: '#? _ == null || typeof _ == "string"',
          previous: '#? _ == null || typeof _ == "string"',
          results: '#[]'
      }
      """
    And match each results[*].id == '#number'
    And match each results[*].images ==
      """
      {
          architecture: '#string',
          features: '#string',
          variant: '#string',
          digest: '#? _ == null || typeof _ == "string"',
          layers: '#[]',
          os: '#string',
          os_features: '#string',
          os_version: '#string',
          size: '#number',
          status: '#string',
          last_pulled: '#? _ == null || typeof _ == "string"',
          last_pushed: '#? _ == null || typeof _ == "string"'
      }
      """
    And match each results[*].images.layers[*].digest == '#? _ == null || typeof _ == "string"'
    And match each results[*].images.layers[*].size == '#number'
    And match each results[*].images.layers[*].instruction == '#string'
    And match each results[*].creator == '#number'
    And match each results[*].last_updated == '#? _ == null || typeof _ == "string"'
    And match each results[*].last_updater == '#number'
    And match each results[*].last_updater_username == '#string'
    And match each results[*].name == '#string'
    And match each results[*].repository == '#number'
    And match each results[*].full_size == '#number'
    And match each results[*].v2 == '#string'
    And match each results[*].status == '#string'
    And match each results[*].tag_last_pulled == '#? _ == null || typeof _ == "string"'
    And match each results[*].tag_last_pushed == '#? _ == null || typeof _ == "string"'

    Examples:
      | namespace | repository | page | page_size | status |
      | 'library' | 'alpine'   |    1 |        10 |    200 |
      | 'library' | 'ubuntu'   |    2 |        20 |    200 |

  Scenario: List repository tags with invalid namespace
    Given path '/v2/namespaces/invalid/repositories/alpine/tags'
    When method get
    Then status 404
    And match response ==
      """
      {
          detail: '#string',
          message: '#string'
      }
      """

  Scenario: List repository tags with invalid repository
    Given path '/v2/namespaces/library/repositories/invalid/tags'
    When method get
    Then status 404
    And match response ==
      """
      {
          detail: '#string',
          message: '#string'
      }
      """

  Scenario: List repository tags with unauthorized access
    Given path '/v2/namespaces/library/repositories/alpine/tags'
    And configure headers = { Authorization: 'Bearer invalid_token', Accept: 'application/json' }
    When method get
    Then status 403
    And match response ==
      """
      {
          detail: '#string',
          message: '#string'
      }
      """
