# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/namespaces/{namespace}/repositories/{repository}/tags/{tag}_get for http method type GET 
# RoostTestHash=f5c1e80f7f
# 
# 

# ********RoostGPT********
Feature: Get Repository Tag

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Get Repository Tag - Valid Input
    Given path '/v2/namespaces/<namespace>/repositories/<repository>/tags/<tag>'
    When method get
    Then status 200
    And match response ==
    """
    {
      "id": '#number',
      "images": {
        "architecture": '#string',
        "features": '#string',
        "variant": '#string',
        "digest": '##string',
        "layers": [
          {
            "digest": '##string',
            "size": '#number',
            "instruction": '#string'
          }
        ],
        "os": '#string',
        "os_features": '#string',
        "os_version": '#string',
        "size": '#number',
        "status": '#string',
        "last_pulled": '##string',
        "last_pushed": '##string'
      },
      "creator": '#number',
      "last_updated": '##string',
      "last_updater": '#number',
      "last_updater_username": '#string',
      "name": '#string',
      "repository": '#number',
      "full_size": '#number',
      "v2": '#string',
      "status": '#string',
      "tag_last_pulled": '##string',
      "tag_last_pushed": '##string'
    }
    """
    Examples:
    | namespace | repository | tag    |
    | myns      | myrepo     | latest |

Scenario: Get Repository Tag - Forbidden
    Given path '/v2/namespaces/nonexistent/repositories/nonexistent/tags/nonexistent'
    When method get
    Then status 403
    And match response ==
    """
    {
      "detail": '#string',
      "message": '#string'
    }
    """

Scenario: Get Repository Tag - Not Found
    Given path '/v2/namespaces/nonexistent/repositories/nonexistent/tags/nonexistent'
    When method get
    Then status 404
    And match response ==
    """
    {
      "detail": '#string',
      "message": '#string'
    }
    """
