# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/namespaces/{namespace}/repositories_get for http method type GET 
# RoostTestHash=6118599531
# 
# 

# ********RoostGPT********
Feature: List repositories in a namespace

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: List repositories in a namespace with valid query parameters
    Given path '/v2/namespaces/<namespace>/repositories'
    And param page = <page>
    And param page_size = <page_size>
    And param name = <name>
    And param ordering = <ordering>
    When method get
    Then status <status>
    And match response == """
    {
        count: '#number',
        next: '#string',
        previous: '#string',
        results: '#[]'
    }
    """
    And match response.count == '#number'
    And match response.next == '#string'
    And match response.previous == '#string'
    And match response.results == '#[]'
    And match each response.results[*].name == '#string'
    And match each response.results[*].namespace == '#string'
    And match each response.results[*].repository_type == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].status == '#number'
    And match each response.results[*].status_description == '#string'
    And match each response.results[*].description == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].is_private == '#boolean'
    And match each response.results[*].star_count == '#number'
    And match each response.results[*].pull_count == '#number'
    And match each response.results[*].last_updated == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].last_modified == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].date_registered == '#string'
    And match each response.results[*].affiliation == '#string'
    And match each response.results[*].media_types == '#[]'
    And match each response.results[*].content_types == '#[]'
    And match each response.results[*].categories == '#[]'
    And match each response.results[*].storage_size == '#number'

    Examples:
      | namespace | page | page_size | name       | ordering        | status |
      | docker   | 1    | 10        | whalesay   | name            | 200    |
      | docker   | 2    | 2         | highland   | -last_updated   | 200    |
      | docker   | 1    | 5         |            | pull_count      | 200    |

  Scenario Outline: List repositories in a namespace with invalid query parameters
    Given path '/v2/namespaces/<namespace>/repositories'
    And param page = <page>
    And param page_size = <page_size>
    And param name = <name>
    And param ordering = <ordering>
    When method get
    Then status <status>
    And match response == """
    {
        fields: { ordering: '#[]' },
        text: '#string'
    }
    """
    And match response.fields.ordering == '#[]'
    And match response.text == '#string'

    Examples:
      | namespace | page | page_size | name       | ordering        | status |
      | docker   | 1    | 10        | whalesay   | invalid_order   | 400    |
      | docker   | 2    | 2         | highland   | -invalid_order  | 400    |
      | docker   | 1    | 5         |            | invalid_order  | 400    |

  Scenario: List repositories in a namespace with unauthorized access
    Given path '/v2/namespaces/docker/repositories'
    When method get
    Then status 401

  Scenario: List repositories in a namespace with forbidden access
    Given path '/v2/namespaces/docker/repositories'
    When method get
    Then status 403

  Scenario: List repositories in a namespace with page not found
    Given path '/v2/namespaces/docker/repositories'
    And param page = 1000
    When method get
    Then status 404
