# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/namespaces/{namespace}/repositories/{repository}/immutabletags_patch for http method type PATCH 
# RoostTestHash=6dc807f428
# 
# 

# ********RoostGPT********
Feature: Update Repository Immutable Tags

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }

Scenario Outline: Update repository immutable tags with valid input
    Given path '/v2/namespaces/<namespace>/repositories/<repository>/immutabletags'
    And request
    """
    {
        "immutable_tags": <immutable_tags>,
        "immutable_tags_rules": <immutable_tags_rules>
    }
    """
    When method put
    Then status 200
    And match response ==
    """
    {
        "user": '#string',
        "name": '#string',
        "namespace": '#string',
        "repository_type": '##string',
        "status": '#number',
        "status_description": '#string',
        "description": '#string',
        "is_private": '#boolean',
        "is_automated": '#boolean',
        "star_count": '#number',
        "pull_count": '#number',
        "last_updated": '#string',
        "last_modified": '##string',
        "date_registered": '#string',
        "collaborator_count": '#number',
        "affiliation": '##string',
        "hub_user": '##string',
        "has_starred": '#boolean',
        "full_description": '##string',
        "permissions": {
            "read": '#boolean',
            "write": '#boolean',
            "admin": '#boolean'
        },
        "media_types": '#[]',
        "content_types": '#[]',
        "categories": '#[]',
        "immutable_tags_settings": {
            "enabled": '#boolean',
            "rules": '#[]'
        },
        "storage_size": '##number'
    }
    """
    Examples:
    | namespace | repository | immutable_tags | immutable_tags_rules |
    | 'namespace1' | 'repository1' | true | ['v.*', '.*-RELEASE'] |
    | 'namespace2' | 'repository2' | false | [] |

Scenario: Update repository immutable tags with missing required fields
    Given path '/v2/namespaces/namespace1/repositories/repository1/immutabletags'
    And request
    """
    {
        "immutable_tags": true
    }
    """
    When method put
    Then status 400
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: Update repository immutable tags with unauthorized access
    Given path '/v2/namespaces/namespace1/repositories/repository1/immutabletags'
    And request
    """
    {
        "immutable_tags": true,
        "immutable_tags_rules": ['v.*', '.*-RELEASE']
    }
    """
    When method put
    Then status 401
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: Update repository immutable tags with forbidden access
    Given path '/v2/namespaces/namespace1/repositories/repository1/immutabletags'
    And request
    """
    {
        "immutable_tags": true,
        "immutable_tags_rules": ['v.*', '.*-RELEASE']
    }
    """
    When method put
    Then status 403
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: Update repository immutable tags with non-existent repository
    Given path '/v2/namespaces/namespace1/repositories/nonExistentRepository/immutabletags'
    And request
    """
    {
        "immutable_tags": true,
        "immutable_tags_rules": ['v.*', '.*-RELEASE']
    }
    """
    When method put
    Then status 404
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'
