# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/namespaces/{namespace}/repositories/{repository}/immutabletags/verify_post for http method type POST 
# RoostTestHash=ba0891e827
# 
# 

# ********RoostGPT********
Feature: Verify repository immutable tags

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Verify immutable tags with valid regex
    Given path '/v2/namespaces/<namespace>/repositories/<repository>/immutabletags/verify'
    And request
    """
    {
        "regex": '<regex>'
    }
    """
    When method POST
    Then status 200
    And match response.tags == '#array'
    And match each response.tags[*].value == '#string'

    Examples:
    | namespace | repository | regex   |
    | myns      | myrepo    | v.*     |
    | myns      | myrepo    | latest  |

Scenario Outline: Verify immutable tags with invalid regex
    Given path '/v2/namespaces/<namespace>/repositories/<repository>/immutabletags/verify'
    And request
    """
    {
        "regex": '<regex>'
    }
    """
    When method POST
    Then status 400
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

    Examples:
    | namespace | repository | regex   |
    | myns      | myrepo    | invalid |
    | myns      | myrepo    | *latest |

Scenario Outline: Verify immutable tags with unauthorized access
    Given path '/v2/namespaces/<namespace>/repositories/<repository>/immutabletags/verify'
    And request
    """
    {
        "regex": '<regex>'
    }
    """
    When method POST
    Then status 401
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

    Examples:
    | namespace | repository | regex   |
    | myns      | myrepo    | v.*     |
    | myns      | myrepo    | latest  |

Scenario Outline: Verify immutable tags with forbidden access
    Given path '/v2/namespaces/<namespace>/repositories/<repository>/immutabletags/verify'
    And request
    """
    {
        "regex": '<regex>'
    }
    """
    When method POST
    Then status 403
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

    Examples:
    | namespace | repository | regex   |
    | myns      | myrepo    | v.*     |
    | myns      | myrepo    | latest  |

Scenario Outline: Verify immutable tags with non-existing repository
    Given path '/v2/namespaces/<namespace>/repositories/<repository>/immutabletags/verify'
    And request
    """
    {
        "regex": '<regex>'
    }
    """
    When method POST
    Then status 404
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

    Examples:
    | namespace | repository | regex   |
    | myns      | myrepo    | v.*     |
    | myns      | myrepo    | latest  |
