# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/groups_post for http method type POST 
# RoostTestHash=e01cff74b7
# 
# 

# ********RoostGPT********
Feature: Create a new group within an organization

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }

  Scenario Outline: Create a new group with valid input
    Given path '/v2/orgs/<org_name>/groups'
    And request
    """
    {
      "name": "<name>",
      "description": "<description>"
    }
    """
    When method POST
    Then status 201
    And match response.id == '##number'
    And match response.uuid == '##string'
    And match response.name == '<name>'
    And match response.description == '<description>'
    And match response.member_count == '##number'

    Examples:
      | org_name | name     | description        |
      | myorg    | mygroup  | Groups description |
      | myorg    | testgroup| Test description   |

  Scenario: Create a new group with missing required field
    Given path '/v2/orgs/myorg/groups'
    And request
    """
    {
      "description": "Groups description"
    }
    """
    When method POST
    Then status 400
    And match response.errinfo == '##object'
    And match response.detail == '##string'
    And match response.message == '##string'

  Scenario: Create a new group with unauthorized access
    Given path '/v2/orgs/myorg/groups'
    And request
    """
    {
      "name": "mygroup",
      "description": "Groups description"
    }
    """
    And configure headers = { Authorization: 'Bearer invalid_token' }
    When method POST
    Then status 401
    And match response.errinfo == '##object'
    And match response.detail == '##string'
    And match response.message == '##string'

  Scenario: Create a new group with forbidden access
    Given path '/v2/orgs/myorg/groups'
    And request
    """
    {
      "name": "mygroup",
      "description": "Groups description"
    }
    """
    When method POST
    Then status 403
    And match response.errinfo == '##object'
    And match response.detail == '##string'
    And match response.message == '##string'
