# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/groups/{group_name}/members_post for http method type POST 
# RoostTestHash=06039a938d
# 
# 

# ********RoostGPT********
Feature: Add member to a group

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json', Authorization: '#(Bearer + karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN'])' }

Scenario Outline: Add a member to a group with valid input
    Given path '/v2/orgs/<org_name>/groups/<group_name>/members'
    And request
    """
    {
        "member": "<member>"
    }
    """
    When method post
    Then status 200
    And match response == '##object'
    And match response.path == '/v2/orgs/<org_name>/groups/<group_name>/members'

    Examples:
    | org_name        | group_name | member   |
    | 'myorganization'| 'developers'| 'jonsnow'|

Scenario Outline: Add a member to a group with invalid input
    Given path '/v2/orgs/<org_name>/groups/<group_name>/members'
    And request
    """
    {
        "member": "<member>"
    }
    """
    When method post
    Then status 400
    And match response == '##object'
    And match response.error == '##object'
    And match response.error.code == '##string'
    And match response.error.message == '##string'

    Examples:
    | org_name        | group_name | member   |
    | 'myorganization'| 'developers'| ''       |

Scenario Outline: Add a member to a group with unauthorized access
    Given path '/v2/orgs/<org_name>/groups/<group_name>/members'
    And request
    """
    {
        "member": "<member>"
    }
    """
    When method post
    Then status 401
    And match response == '##object'
    And match response.error == '##object'
    And match response.error.code == '##string'
    And match response.error.message == '##string'

    Examples:
    | org_name        | group_name | member   |
    | 'myorganization'| 'developers'| 'jonsnow'|

Scenario Outline: Add a member to a group with forbidden access
    Given path '/v2/orgs/<org_name>/groups/<group_name>/members'
    And request
    """
    {
        "member": "<member>"
    }
    """
    When method post
    Then status 403
    And match response == '##object'
    And match response.error == '##object'
    And match response.error.code == '##string'
    And match response.error.message == '##string'

    Examples:
    | org_name        | group_name | member   |
    | 'myorganization'| 'developers'| 'jonsnow'|

Scenario Outline: Add a member to a group with not found
    Given path '/v2/orgs/<org_name>/groups/<group_name>/members'
    And request
    """
    {
        "member": "<member>"
    }
    """
    When method post
    Then status 404
    And match response == '##object'
    And match response.error == '##object'
    And match response.error.code == '##string'
    And match response.error.message == '##string'

    Examples:
    | org_name        | group_name | member   |
    | 'myorganization'| 'developers'| 'jonsnow'|

Scenario Outline: Add a member to a group with internal server error
    Given path '/v2/orgs/<org_name>/groups/<group_name>/members'
    And request
    """
    {
        "member": "<member>"
    }
    """
    When method post
    Then status 500
    And match response == '##object'
    And match response.error == '##object'
    And match response.error.code == '##string'
    And match response.error.message == '##string'

    Examples:
    | org_name        | group_name | member   |
    | 'myorganization'| 'developers'| 'jonsnow'|
