# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/access-tokens/{access_token_id}_get for http method type GET 
# RoostTestHash=eb5bdfcb2b
# 
# 

# ********RoostGPT********
Feature: Get access token

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Get access token with valid org_name and access_token_id
    Given path '/v2/orgs/<org_name>/access-tokens/<access_token_id>'
    When method get
    Then status 200
    And match response.id == '#string'
    And match response.label == '#string'
    And match response.created_by == '#string'
    And match response.is_active == '#boolean'
    And match response.created_at == '#string'
    And match response.expires_at == '##string'
    And match response.last_used_at == '##string'
    And match response.resources == '#array'
    And match each response.resources[*].type == '#string'
    And match each response.resources[*].path == '#string'
    And match each response.resources[*].scopes == '#array'
    And match each response.resources[*].scopes[*].type == '#string'

    Examples:
        | org_name      | access_token_id                              |
        | 'myorg'       | 'a7a5ef25-8889-43a0-8cc7-f2a94268e861'      |
        | 'anotherorg'  | 'b8b6ef36-999a-54b1-9dd8-e3b0c4429810'      |

Scenario: Get access token with invalid org_name
    Given path '/v2/orgs/invalidorg/access-tokens/a7a5ef25-8889-43a0-8cc7-f2a94268e861'
    When method get
    Then status 404
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: Get access token with invalid access_token_id
    Given path '/v2/orgs/myorg/access-tokens/invalidtoken'
    When method get
    Then status 404
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: Get access token with unauthorized access
    Given path '/v2/orgs/myorg/access-tokens/a7a5ef25-8889-43a0-8cc7-f2a94268e861'
    And configure headers = { Authorization: 'Bearer invalidtoken', Accept: 'application/json' }
    When method get
    Then status 401
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: Get access token with forbidden access
    Given path '/v2/orgs/myorg/access-tokens/a7a5ef25-8889-43a0-8cc7-f2a94268e861'
    And configure headers = { Authorization: 'Bearer forbiddentoken', Accept: 'application/json' }
    When method get
    Then status 403
    And match response.detail == '#string'
    And match response.message == '#string'
