# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{name}/access-tokens_get for http method type GET 
# RoostTestHash=3c3e591758
# 
# 

# ********RoostGPT********
Feature: List access tokens for an organization

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: List access tokens for an organization with valid query parameters
    Given path '/v2/orgs/<org_name>/access-tokens'
    And param page = <page>
    And param page_size = <page_size>
    When method get
    Then status <status_code>
    And match response ==
    """
    {
      total: '#number',
      next: '#? _ == null || typeof _ == "string"',
      previous: '#? _ == null || typeof _ == "string"',
      results: '#? _ == null || typeof _ == "array"'
    }
    """
    And match each results[*].id == '#string'
    And match each results[*].label == '#string'
    And match each results[*].created_by == '#string'
    And match each results[*].is_active == '#boolean'
    And match each results[*].created_at == '#string'
    And match each results[*].expires_at == '#? _ == null || typeof _ == "string"'
    And match each results[*].last_used_at == '#? _ == null || typeof _ == "string"'

    Examples:
      | org_name | page | page_size | status_code |
      | docker   | 1    | 10        | 200         |
      | docker   | 2    | 10        | 200         |
      | docker   | 3    | 10        | 200         |

  Scenario: List access tokens for an organization with invalid authorization
    Given path '/v2/orgs/docker/access-tokens'
    When method get
    Then status 401
    And match response ==
    """
    {
      detail: '#string',
      message: '#string'
    }
    """

  Scenario: List access tokens for an organization with forbidden access
    Given path '/v2/orgs/docker/access-tokens'
    When method get
    Then status 403
    And match response ==
    """
    {
      detail: '#string',
      message: '#string'
    }
    """

  Scenario: List access tokens for an organization that does not exist
    Given path '/v2/orgs/nonexistent/access-tokens'
    When method get
    Then status 404
    And match response ==
    """
    {
      detail: '#string',
      message: '#string'
    }
    """
