# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/groups_get for http method type GET 
# RoostTestHash=9f16c032e9
# 
# 

# ********RoostGPT********
Feature: Get groups of an organization

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Get groups of an organization with valid parameters
    Given path '/v2/orgs/<org_name>/groups'
    And param page = <page>
    And param page_size = <page_size>
    And param username = '<username>'
    And param search = '<search>'
    When method get
    Then status <status>
    And match response ==
    """
    {
      count: '#number',
      next: '#? _ == null || typeof _ == "string"',
      previous: '#? _ == null || typeof _ == "string"',
      results: '#[]'
    }
    """
    And match each results[*].id == '#number'
    And match each results[*].uuid == '#string'
    And match each results[*].name == '#string'
    And match each results[*].description == '#string'
    And match each results[*].member_count == '#number'

    Examples:
      | org_name | page | page_size | username | search | status |
      | myorg    | 1     | 10        | user1    | group1 | 200    |
      | myorg    | 2     | 5         | user2    | group2 | 200    |

  Scenario: Get groups of an organization with invalid authorization
    Given path '/v2/orgs/myorg/groups'
    When method get
    Then status 401
    And match response ==
    """
    {
      errinfo: '#object',
      detail: '#string',
      message: '#string'
    }
    """

  Scenario: Get groups of an organization with forbidden access
    Given path '/v2/orgs/myorg/groups'
    When method get
    Then status 403
    And match response ==
    """
    {
      errinfo: '#object',
      detail: '#string',
      message: '#string'
    }
    """

  Scenario: Get groups of an organization with non-existent organization
    Given path '/v2/orgs/nonexistentorg/groups'
    When method get
    Then status 404
    And match response ==
    """
    {
      errinfo: '#object',
      detail: '#string',
      message: '#string'
    }
    """
