# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/groups/{group_name}_patch for http method type PATCH 
# RoostTestHash=f4023fcc72
# 
# 

# ********RoostGPT********
Feature: Update organization group details

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Update group details with valid input
    Given path '/v2/orgs/<org_name>/groups/<group_name>'
    And request
    """
    {
      "name": "<name>",
      "description": "<description>"
    }
    """
    When method put
    Then status 200
    And match response.id == '#number'
    And match response.uuid == '#string'
    And match response.name == '<name>'
    And match response.description == '<description>'
    And match response.member_count == '#number'

    Examples:
      | org_name | group_name | name       | description      |
      | myorg    | mygroup    | newname    | new description  |
      | myorg    | mygroup    | mygroup    | Groups description|

  Scenario Outline: Update group details with invalid authorization
    Given path '/v2/orgs/<org_name>/groups/<group_name>'
    And request
    """
    {
      "name": "<name>",
      "description": "<description>"
    }
    """
    When method put
    Then status 401
    And match response.errinfo == '##object'
    And match response.detail == '#string'
    And match response.message == '#string'

    Examples:
      | org_name | group_name | name       | description      |
      | myorg    | mygroup    | newname    | new description  |

  Scenario Outline: Update group details with forbidden access
    Given path '/v2/orgs/<org_name>/groups/<group_name>'
    And request
    """
    {
      "name": "<name>",
      "description": "<description>"
    }
    """
    When method put
    Then status 403
    And match response.errinfo == '##object'
    And match response.detail == '#string'
    And match response.message == '#string'

    Examples:
      | org_name | group_name | name       | description      |
      | myorg    | mygroup    | newname    | new description  |

  Scenario Outline: Update group details with non-existing group
    Given path '/v2/orgs/<org_name>/groups/<group_name>'
    And request
    """
    {
      "name": "<name>",
      "description": "<description>"
    }
    """
    When method put
    Then status 404
    And match response.errinfo == '##object'
    And match response.detail == '#string'
    And match response.message == '#string'

    Examples:
      | org_name | group_name | name       | description      |
      | myorg    | mygroup    | newname    | new description  |
