# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/groups/{group_name}_put for http method type PUT 
# RoostTestHash=2337372512
# 
# 

# ********RoostGPT********
Feature: Update Organization Group Details

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Update Organization Group Details - Valid Input
    Given path '/v2/orgs/<org_name>/groups/<group_name>'
    And request
    """
    {
        "name": '<name>',
        "description": '<description>'
    }
    """
    When method PUT
    Then status 200
    And match response.id == '#number'
    And match response.uuid == '#string'
    And match response.name == '<name>'
    And match response.description == '<description>'
    And match response.member_count == '#number'

    Examples:
    | org_name | group_name | name      | description       |
    | org1     | group1     | newgroup  | New group desc    |
    | org2     | group2     | group2    | Group 2 description|

Scenario Outline: Update Organization Group Details - Invalid Input
    Given path '/v2/orgs/<org_name>/groups/<group_name>'
    And request
    """
    {
        "name": '<name>',
        "description": '<description>'
    }
    """
    When method PUT
    Then status <status_code>
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

    Examples:
    | org_name | group_name | name      | description       | status_code |
    | org1     | group1     | ''        | Invalid desc      | 400         |
    | org2     | group2     | newgroup  | ''                | 400         |
    | org3     | group3     | newgroup  | New group desc    | 401         |
    | org4     | group4     | newgroup  | New group desc    | 403         |
    | org5     | group5     | newgroup  | New group desc    | 404         |
