# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{name}/access-tokens_post for http method type POST 
# RoostTestHash=0fa2fad0ee
# 
# 

# ********RoostGPT********
Feature: Create access token for an organization

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Create access token with valid input
    Given path '/v2/orgs/<org_name>/access-tokens'
    And request
    """
    {
        "label": "<label>",
        "description": "<description>",
        "resources": <resources>,
        "expires_at": "<expires_at>"
    }
    """
    When method POST
    Then status 201
    And match response.id == '#string'
    And match response.label == '#string'
    And match response.created_by == '#string'
    And match response.is_active == '#boolean'
    And match response.created_at == '#string'
    And match response.expires_at == '#? _ == null || typeof _ == "string"'
    And match response.last_used_at == '#? _ == null || typeof _ == "string"'
    And match response.token == '#string'
    And match each response.resources[*].type == '#string'
    And match each response.resources[*].path == '#string'
    And match each response.resources[*].scopes == '#array'

    Examples:
    | org_name | label               | description            | resources                                                                 | expires_at           |
    | myorg    | My organization token | Token for CI/CD pipeline | [{"type": "TYPE_REPO", "path": "myorg/myrepo", "scopes": ["repo-pull"]}] | 2023-05-20T00:54:18Z |

Scenario: Create access token with missing required field
    Given path '/v2/orgs/myorg/access-tokens'
    And request
    """
    {
        "description": "Token for CI/CD pipeline",
        "resources": [{"type": "TYPE_REPO", "path": "myorg/myrepo", "scopes": ["repo-pull"]}],
        "expires_at": "2023-05-20T00:54:18Z"
    }
    """
    When method POST
    Then status 400
    And match response.fields == '#object'
    And match response.text == '#string'

Scenario: Create access token with invalid authorization
    Given path '/v2/orgs/myorg/access-tokens'
    And request
    """
    {
        "label": "My organization token",
        "description": "Token for CI/CD pipeline",
        "resources": [{"type": "TYPE_REPO", "path": "myorg/myrepo", "scopes": ["repo-pull"]}],
        "expires_at": "2023-05-20T00:54:18Z"
    }
    """
    And configure headers = { Authorization: 'Bearer invalid_token', Accept: 'application/json' }
    When method POST
    Then status 401
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: Create access token with forbidden access
    Given path '/v2/orgs/myorg/access-tokens'
    And request
    """
    {
        "label": "My organization token",
        "description": "Token for CI/CD pipeline",
        "resources": [{"type": "TYPE_REPO", "path": "myorg/myrepo", "scopes": ["repo-pull"]}],
        "expires_at": "2023-05-20T00:54:18Z"
    }
    """
    When method POST
    Then status 403
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: Create access token for non-existing organization
    Given path '/v2/orgs/nonexistentorg/access-tokens'
    And request
    """
    {
        "label": "My organization token",
        "description": "Token for CI/CD pipeline",
        "resources": [{"type": "TYPE_REPO", "path": "myorg/myrepo", "scopes": ["repo-pull"]}],
        "expires_at": "2023-05-20T00:54:18Z"
    }
    """
    When method POST
    Then status 404
    And match response.detail == '#string'
    And match response.message == '#string'
