# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/invites_get for http method type GET 
# RoostTestHash=a2f41687bd
# 
# 

# ********RoostGPT********
Feature: List org invites

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario: List org invites with valid org name
    Given path '/v2/orgs', 'org_name', '/invites'
    When method get
    Then status 200
    And match response.data == '#[]'
    And match response.data[*].id == '#string'
    And match response.data[*].inviter_username == '#string'
    And match response.data[*].invitee == '#string'
    And match response.data[*].org == '#string'
    And match response.data[*].team == '#string'
    And match response.data[*].created_at == '#string'

Scenario: List org invites with invalid org name
    Given path '/v2/orgs', 'invalid_org_name', '/invites'
    When method get
    Then status 404
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: List org invites with unauthorized access
    Given path '/v2/orgs', 'org_name', '/invites'
    And configure headers = { Authorization: 'Bearer invalid_token', Accept: 'application/json' }
    When method get
    Then status 401
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: List org invites with forbidden access
    Given path '/v2/orgs', 'org_name', '/invites'
    And configure headers = { Authorization: 'Bearer forbidden_token', Accept: 'application/json' }
    When method get
    Then status 403
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'
