# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/access-tokens/{access_token_id}_patch for http method type PATCH 
# RoostTestHash=4ddebba703
# 
# 

# ********RoostGPT********
Feature: Update access token

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Update access token with valid payload
    Given path '/v2/orgs/<org_name>/access-tokens/<access_token_id>'
    And request
    """
    {
        "label": "<label>",
        "description": "<description>",
        "resources": <resources>,
        "is_active": <is_active>
    }
    """
    When method put
    Then status 200
    And match response ==
    """
    {
        "id": "#string",
        "label": "<label>",
        "created_by": "#string",
        "is_active": <is_active>,
        "created_at": "#string",
        "expires_at": "##string",
        "last_used_at": "##string",
        "resources": <resources>
    }
    """
    Examples:
        | org_name       | access_token_id             | label                 | description            | resources                                                                 | is_active |
        | myorg          | a7a5ef25-8889-43a0-8cc7-f2a94268e861 | My organization token | Token for CI/CD pipeline | [{"type": 'TYPE_REPO', "path": 'myorg/myrepo', "scopes": ['repo-pull']}] | true      |

Scenario: Update access token with missing authorization
    Given path '/v2/orgs/myorg/access-tokens/a7a5ef25-8889-43a0-8cc7-f2a94268e861'
    And request
    """
    {
        "label": "My organization token",
        "description": "Token for CI/CD pipeline",
        "resources": [{"type": 'TYPE_REPO', "path": 'myorg/myrepo', "scopes": ['repo-pull']}],
        "is_active": true
    }
    """
    When method put
    Then status 401
    And match response ==
    """
    {
        "detail": "#string",
        "message": "#string"
    }
    """

Scenario: Update access token with invalid org_name
    Given path '/v2/orgs/invalidorg/access-tokens/a7a5ef25-8889-43a0-8cc7-f2a94268e861'
    And request
    """
    {
        "label": "My organization token",
        "description": "Token for CI/CD pipeline",
        "resources": [{"type": 'TYPE_REPO', "path": 'myorg/myrepo', "scopes": ['repo-pull']}],
        "is_active": true
    }
    """
    When method put
    Then status 403
    And match response ==
    """
    {
        "detail": "#string",
        "message": "#string"
    }
    """

Scenario: Update access token with invalid access_token_id
    Given path '/v2/orgs/myorg/access-tokens/invalidtoken'
    And request
    """
    {
        "label": "My organization token",
        "description": "Token for CI/CD pipeline",
        "resources": [{"type": 'TYPE_REPO', "path": 'myorg/myrepo', "scopes": ['repo-pull']}],
        "is_active": true
    }
    """
    When method put
    Then status 404
    And match response ==
    """
    {
        "detail": "#string",
        "message": "#string"
    }
    """
