# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/members/{username}_delete for http method type DELETE 
# RoostTestHash=10660b3aa8
# 
# 

# ********RoostGPT********
Feature: Remove member from org

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Remove member from org
    * def org_name = <org_name>
    * def username = <username>
    * delete /v2/orgs/#(org_name)/members/#(username)
    * assert responseStatus == 204

    Examples:
    | org_name | username |
    | 'org1'   | 'user1'  |
    | 'org2'   | 'user2'  |

Scenario Outline: Remove member from org - Bad Request
    * def org_name = <org_name>
    * def username = <username>
    * delete /v2/orgs/#(org_name)/members/#(username)
    * assert responseStatus == 400
    * match response contains { errinfo: '#object', detail: '#string', message: '#string' }

    Examples:
    | org_name | username |
    | 'org1'   | 'user1'  |
    | 'org2'   | 'user2'  |

Scenario Outline: Remove member from org - Unauthorized
    * def org_name = <org_name>
    * def username = <username>
    * delete /v2/orgs/#(org_name)/members/#(username)
    * assert responseStatus == 401
    * match response contains { errinfo: '#object', detail: '#string', message: '#string' }

    Examples:
    | org_name | username |
    | 'org1'   | 'user1'  |
    | 'org2'   | 'user2'  |

Scenario Outline: Remove member from org - Forbidden
    * def org_name = <org_name>
    * def username = <username>
    * delete /v2/orgs/#(org_name)/members/#(username)
    * assert responseStatus == 403
    * match response contains { errinfo: '#object', detail: '#string', message: '#string' }

    Examples:
    | org_name | username |
    | 'org1'   | 'user1'  |
    | 'org2'   | 'user2'  |

Scenario Outline: Remove member from org - Not Found
    * def org_name = <org_name>
    * def username = <username>
    * delete /v2/orgs/#(org_name)/members/#(username)
    * assert responseStatus == 404
    * match response contains { errinfo: '#object', detail: '#string', message: '#string' }

    Examples:
    | org_name | username |
    | 'org1'   | 'user1'  |
    | 'org2'   | 'user2'  |
