# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/members_get for http method type GET 
# RoostTestHash=dde05efa3a
# 
# 

# ********RoostGPT********
Feature: List org members

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: List org members with valid org_name
    Given path '/v2/orgs/<org_name>/members'
    When method get
    Then status 200
    And match response == '#array'
    And match response[*].count == '#number'
    And match response[*].previous == '#string'
    And match response[*].next == '#string'
    And match response[*].results == '#array'
    And match response[*].results[*].id == '#string'
    And match response[*].results[*].company == '#string'
    And match response[*].results[*].date_joined == '#string'
    And match response[*].results[*].full_name == '#string'
    And match response[*].results[*].gravatar_email == '#string'
    And match response[*].results[*].gravatar_url == '#string'
    And match response[*].results[*].location == '#string'
    And match response[*].results[*].profile_url == '#string'
    And match response[*].results[*].type == '#string'
    And match response[*].results[*].username == '#string'
    And match response[*].results[*].email == '#string'
    And match response[*].results[*].role == '#string'
    And match response[*].results[*].groups == '#array'
    And match response[*].results[*].is_guest == '#boolean'
    And match response[*].results[*].primary_email == '#string'
    And match response[*].results[*].last_logged_in_at == '#string'
    And match response[*].results[*].last_seen_at == '#string'
    And match response[*].results[*].last_desktop_version == '#string'

    Examples:
        | org_name         |
        | 'docker'         |
        | 'github'         |

Scenario Outline: List org members with invalid org_name
    Given path '/v2/orgs/<org_name>/members'
    When method get
    Then status 404
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

    Examples:
        | org_name         |
        | 'invalid_org'    |

Scenario: List org members without authorization
    Given path '/v2/orgs/docker/members'
    When method get
    Then status 401
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: List org members with invalid authorization
    Given path '/v2/orgs/docker/members'
    And configure headers = { Authorization: 'Bearer invalid_token', Accept: 'application/json' }
    When method get
    Then status 401
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'
