# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/groups/{group_name}_get for http method type GET 
# RoostTestHash=68dfd51d23
# 
# 

# ********RoostGPT********
Feature: Get a group of an organization

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Get a group of an organization - Success
    Given path '/v2/orgs/<org_name>/groups/<group_name>'
    When method get
    Then status 200
    And match response ==
    """
    {
      id: '#number',
      uuid: '#string',
      name: '#string',
      description: '#string',
      member_count: '#number'
    }
    """

    Examples:
    | org_name | group_name |
    | 'org1'   | 'group1'   |
    | 'org2'   | 'group2'   |

Scenario: Get a group of an organization - Unauthorized
    Given path '/v2/orgs/org1/groups/group1'
    When method get
    Then status 401
    And match response ==
    """
    {
      errinfo: '#object',
      detail: '#string',
      message: '#string'
    }
    """

Scenario: Get a group of an organization - Forbidden
    Given path '/v2/orgs/org1/groups/group1'
    When method get
    Then status 403
    And match response ==
    """
    {
      errinfo: '#object',
      detail: '#string',
      message: '#string'
    }
    """

Scenario: Get a group of an organization - Not Found
    Given path '/v2/orgs/org1/groups/group1'
    When method get
    Then status 404
    And match response ==
    """
    {
      errinfo: '#object',
      detail: '#string',
      message: '#string'
    }
    """
