# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{name}/settings_put for http method type PUT 
# RoostTestHash=d844cdb455
# 
# 

# ********RoostGPT********
Feature: Update Organization Settings

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Update Organization Settings with Valid Input
    Given path '/v2/orgs/<org_name>/settings'
    And request
    """
    {
      "restricted_images": {
        "enabled": <enabled>,
        "allow_official_images": <allow_official_images>,
        "allow_verified_publishers": <allow_verified_publishers>
      }
    }
    """
    When method put
    Then status 200
    And match response ==
    """
    {
      "restricted_images": {
        "enabled": <enabled>,
        "allow_official_images": <allow_official_images>,
        "allow_verified_publishers": <allow_verified_publishers>
      }
    }
    """
    And match response.restricted_images.enabled == '#boolean'
    And match response.restricted_images.allow_official_images == '#boolean'
    And match response.restricted_images.allow_verified_publishers == '#boolean'

    Examples:
      | org_name  | enabled | allow_official_images | allow_verified_publishers |
      | 'myorg'   | true    | true                   | true                     |
      | 'myorg'   | false   | false                  | false                    |

  Scenario: Update Organization Settings with Missing Required Fields
    Given path '/v2/orgs/myorg/settings'
    And request
    """
    {
      "restricted_images": {
        "enabled": true
      }
    }
    """
    When method put
    Then status 400
    And match response.error.code == '#number'
    And match response.error.message == '#string'

  Scenario: Update Organization Settings with Unauthorized Access
    Given path '/v2/orgs/myorg/settings'
    And request
    """
    {
      "restricted_images": {
        "enabled": true,
        "allow_official_images": true,
        "allow_verified_publishers": true
      }
    }
    """
    When method put
    Then status 401
    And match response.detail == '#string'
    And match response.message == '#string'

  Scenario: Update Organization Settings with Forbidden Access
    Given path '/v2/orgs/myorg/settings'
    And request
    """
    {
      "restricted_images": {
        "enabled": true,
        "allow_official_images": true,
        "allow_verified_publishers": true
      }
    }
    """
    When method put
    Then status 403
    And match response.detail == '#string'
    And match response.message == '#string'

  Scenario: Update Organization Settings with Non-Existent Organization
    Given path '/v2/orgs/nonexistentorg/settings'
    And request
    """
    {
      "restricted_images": {
        "enabled": true,
        "allow_official_images": true,
        "allow_verified_publishers": true
      }
    }
    """
    When method put
    Then status 404
    And match response.detail == '#string'
    And match response.message == '#string'
