# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/groups/{group_name}/members_get for http method type GET 
# RoostTestHash=5d1922314f
# 
# 

# ********RoostGPT********
Feature: List members of a group

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: List members of a group with valid parameters
    Given path '/v2/orgs/<org_name>/groups/<group_name>/members'
    And param page = <page>
    And param page_size = <page_size>
    And param search = '<search>'
    When method get
    Then status <status>
    And match response ==
      """
      {
        count: '#number',
        next: '#? _ == null || typeof _ == "string"',
        previous: '#? _ == null || typeof _ == "string"',
        results: '#([])'
      }
      """
    And match each response.results[*].id == '#string'
    And match each response.results[*].company == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].date_joined == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].full_name == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].gravatar_email == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].gravatar_url == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].location == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].profile_url == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].type == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].username == '#? _ == null || typeof _ == "string"'
    And match each response.results[*].email == '#? _ == null || typeof _ == "string"'

    Examples:
      | org_name         | group_name   | page | page_size | search       | status |
      | 'myorganization' | 'developers' |    1 |        10 | ''           |    200 |
      | 'myorganization' | 'developers' |    2 |         5 | 'dockeruser' |    200 |

  Scenario: List members of a group with invalid authorization
    Given path '/v2/orgs/myorganization/groups/developers/members'
    When method get
    Then status 401
    And match response ==
      """
      {
        errinfo: '#object',
        detail: '#string',
        message: '#string'
      }
      """

  Scenario: List members of a group with forbidden access
    Given path '/v2/orgs/myorganization/groups/developers/members'
    When method get
    Then status 403
    And match response ==
      """
      {
        errinfo: '#object',
        detail: '#string',
        message: '#string'
      }
      """

  Scenario: List members of a group with non-existent group
    Given path '/v2/orgs/myorganization/groups/nonexistent/members'
    When method get
    Then status 404
    And match response ==
      """
      {
        errinfo: '#object',
        detail: '#string',
        message: '#string'
      }
      """
