# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{name}/settings_get for http method type GET 
# RoostTestHash=6f5e4c65aa
# 
# 

# ********RoostGPT********
Feature: Get Organization Settings

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Get organization settings with valid name
    Given path '/v2/orgs/<name>/settings'
    When method get
    Then status 200
    And match response.restricted_images == { enabled: '#boolean', allow_official_images: '#boolean', allow_verified_publishers: '#boolean' }
    Examples:
        | name      |
        | 'org1'    |
        | 'org2'    |

Scenario: Get organization settings with unauthorized access
    Given path '/v2/orgs/non_existent_org/settings'
    When method get
    Then status 401
    And match response == { detail: '#string', message: '#string' }

Scenario: Get organization settings with forbidden access
    Given path '/v2/orgs/forbidden_org/settings'
    When method get
    Then status 403
    And match response == { detail: '#string', message: '#string' }

Scenario: Get organization settings with non-existent organization
    Given path '/v2/orgs/non_existent_org/settings'
    When method get
    Then status 404
    And match response == { detail: '#string', message: '#string' }
