# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/groups/{group_name}/members/{username}_delete for http method type DELETE 
# RoostTestHash=5efaab73dc
# 
# 

# ********RoostGPT********
Feature: Remove a user from a group

Background:
* def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
* url baseURL
* configure headers = { Accept: 'application/json' }
* def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
* configure headers = { Authorization: '#(authToken)' }

Scenario Outline: Remove a user from a group
Given path '/v2/orgs/<org_name>/groups/<group_name>/members/<username>'
When method DELETE
Then status <status_code>
And match response == '#? _ == null || typeof _ == "object"'
And match response.errinfo == '#? _ == null || typeof _ == "object"'
And match response.errinfo.* == '#? _ == null || typeof _ == "string"'
And match response.detail == '#? _ == null || typeof _ == "string"'
And match response.message == '#? _ == null || typeof _ == "string"'

Examples:
| org_name | group_name | username | status_code |
| 'org1'   | 'group1'   | 'user1'  | 204         |
| 'org1'   | 'group1'   | 'user1'  | 401         |
| 'org1'   | 'group1'   | 'user1'  | 403         |
| 'org1'   | 'group1'   | 'user1'  | 404         |
