# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/groups/{group_name}_delete for http method type DELETE 
# RoostTestHash=04dfef2b01
# 
# 

# ********RoostGPT********
Feature: Delete an organization group

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }

  Scenario Outline: Delete an organization group
    Given path '/v2/orgs/<org_name>/groups/<group_name>'
    When method delete
    Then status <status_code>
    * def responseBody = response
    * def errinfo = responseBody.errinfo
    * def detail = responseBody.detail
    * def message = responseBody.message

    Examples:
      | org_name | group_name | status_code |
      | 'org1'   | 'group1'   | 204         |
      | 'org2'   | 'group2'   | 401         |
      | 'org3'   | 'group3'   | 403         |
      | 'org4'   | 'group4'   | 404         |

  Scenario: Delete an organization group - 204 response
    Given path '/v2/orgs/org1/groups/group1'
    When method delete
    Then status 204

  Scenario: Delete an organization group - 401 response
    Given path '/v2/orgs/org2/groups/group2'
    When method delete
    Then status 401
    And match responseBody == { errinfo: '##object', detail: '##string', message: '##string' }

  Scenario: Delete an organization group - 403 response
    Given path '/v2/orgs/org3/groups/group3'
    When method delete
    Then status 403
    And match responseBody == { errinfo: '##object', detail: '##string', message: '##string' }

  Scenario: Delete an organization group - 404 response
    Given path '/v2/orgs/org4/groups/group4'
    When method delete
    Then status 404
    And match responseBody == { errinfo: '##object', detail: '##string', message: '##string' }
