# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/access-tokens/{access_token_id}_delete for http method type DELETE 
# RoostTestHash=a68b459567
# 
# 

# ********RoostGPT********
Feature: Delete access token for an organization

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Delete access token for an organization
    Given path '/v2/orgs/<org_name>/access-tokens/<access_token_id>'
    When method delete
    Then status <expected_status>
    And match response == '#? _ == null || typeof _ == "object"'
    * if (responseStatus == 401 || responseStatus == 403 || responseStatus == 404) *
    And match response.detail == '##string'
    And match response.message == '##string'

Examples:
    | org_name       | access_token_id | expected_status |
    | 'org1'         | 1               | 204              |
    | 'org2'         | 2               | 401              |
    | 'org3'         | 3               | 403              |
    | 'org4'         | 4               | 404              |
