# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/members/export_get for http method type GET 
# RoostTestHash=9419550c2a
# 
# 

# ********RoostGPT********
Feature: Export Organization Members CSV

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Export members of an organization as a CSV
    Given path '/v2/orgs/<org_name>/members/export'
    When method get
    Then status 200
    And match responseHeaders['Content-Disposition'] contains 'attachment;filename="<org_name>-members-'
    And match response == '#[]'
    And match each response[*].Name == '##string'
    And match each response[*].Username == '##string'
    And match each response[*].Email == '##string'
    And match each response[*].Type == '##string'
    And match each response[*].Permission == '##string'
    And match each response[*].Teams == '##string'
    And match each response[*].'Date Joined' == '##string'

    Examples:
      | org_name  |
      | 'org1'    |
      | 'org2'    |

  Scenario Outline: Export members of an organization as a CSV - Invalid Organization
    Given path '/v2/orgs/<org_name>/members/export'
    When method get
    Then status 404
    And match response.errinfo == '#object'
    And match response.detail == '##string'
    And match response.message == '##string'

    Examples:
      | org_name  |
      | 'invalid' |

  Scenario Outline: Export members of an organization as a CSV - Unauthorized
    Given path '/v2/orgs/<org_name>/members/export'
    When method get
    Then status 401
    And match response.errinfo == '#object'
    And match response.detail == '##string'
    And match response.message == '##string'

    Examples:
      | org_name  |
      | 'org1'    |

  Scenario Outline: Export members of an organization as a CSV - Forbidden
    Given path '/v2/orgs/<org_name>/members/export'
    When method get
    Then status 403
    And match response.errinfo == '#object'
    And match response.detail == '##string'
    And match response.message == '##string'

    Examples:
      | org_name  |
      | 'org1'    |

  Scenario Outline: Export members of an organization as a CSV - Bad Request
    Given path '/v2/orgs/<org_name>/members/export'
    When method get
    Then status 400
    And match response.errinfo == '#object'
    And match response.detail == '##string'
    And match response.message == '##string'

    Examples:
      | org_name  |
      | 'org1'    |
