# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/orgs/{org_name}/members/{username}_put for http method type PUT 
# RoostTestHash=ad4405d68a
# 
# 

# ********RoostGPT********
Feature: Update org member role

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }

Scenario Outline: Update org member role with valid data
    Given path '/v2/orgs/<org_name>/members/<username>'
    And request
    """
    {
        "role": '<role>'
    }
    """
    When method put
    Then status 200
    And match response.id == '#string'
    And match response.company == '#string'
    And match response.date_joined == '#string'
    And match response.full_name == '#string'
    And match response.gravatar_email == '#string'
    And match response.gravatar_url == '#string'
    And match response.location == '#string'
    And match response.profile_url == '#string'
    And match response.type == '#string'
    And match response.username == '#string'
    And match response.email == '#string'
    And match response.role == '#string'
    And match response.groups == '#array'
    And match response.is_guest == '#boolean'
    And match response.primary_email == '#string'
    And match response.last_logged_in_at == '#string'
    And match response.last_seen_at == '#string'
    And match response.last_desktop_version == '#string'

    Examples:
        | org_name  | username  | role    |
        | 'docker'  | 'user1'   | 'Owner' |
        | 'docker'  | 'user2'   | 'Admin' |

Scenario: Update org member role with missing role
    Given path '/v2/orgs/<org_name>/members/<username>'
    And request
    """
    {
    }
    """
    When method put
    Then status 400
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: Update org member role with unauthorized access
    Given path '/v2/orgs/<org_name>/members/<username>'
    And request
    """
    {
        "role": 'Owner'
    }
    """
    And configure headers = { Authorization: 'Bearer invalid_token' }
    When method put
    Then status 401
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: Update org member role with forbidden access
    Given path '/v2/orgs/<org_name>/members/<username>'
    And request
    """
    {
        "role": 'Owner'
    }
    """
    When method put
    Then status 403
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'

Scenario: Update org member role for non-existent member
    Given path '/v2/orgs/<org_name>/members/<username>'
    And request
    """
    {
        "role": 'Owner'
    }
    """
    When method put
    Then status 404
    And match response.errinfo == '#object'
    And match response.detail == '#string'
    And match response.message == '#string'
