# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/repositories/{namespace}/{repository}/groups_post for http method type POST 
# RoostTestHash=c4499be632
# 
# 

# ********RoostGPT********
Feature: Assign a group (Team) to a repository for access

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Assign a group to a repository for access
    Given path '/v2/repositories/<namespace>/<repository>/groups'
    And param group_name = '<group_name>'
    And param permission = '<permission>'
    When method GET
    Then status <status>
    And match response ==
    """
    {
      group_name: '#string',
      permission: '#string'
    }
    """
    Examples:
    | namespace | repository | group_name | permission | status |
    | my_namespace | my_repository | my_group | read | 200 |
    | my_namespace | my_repository | my_group | write | 200 |
    | my_namespace | my_repository | my_group | admin | 200 |

Scenario: Assign a group to a repository for access with invalid permission
    Given path '/v2/repositories/my_namespace/my_repository/groups'
    And param group_name = 'my_group'
    And param permission = 'invalid_permission'
    When method GET
    Then status 403
    And match response ==
    """
    {
      errinfo: '#? _ == null || typeof _ == "object"',
      detail: '#string',
      message: '#string'
    }
    """

Scenario: Assign a group to a repository for access with invalid namespace
    Given path '/v2/repositories/invalid_namespace/my_repository/groups'
    And param group_name = 'my_group'
    And param permission = 'read'
    When method GET
    Then status 404
    And match response ==
    """
    {
      detail: '#string',
      message: '#string'
    }
    """
