# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/scim/2.0/Users/{id}_get for http method type GET 
# RoostTestHash=27797237ec
# 
# 

# ********RoostGPT********
Feature: Get a user by ID

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Get a user with valid ID
    Given path '/v2/scim/2.0/Users/<id>'
    When method get
    Then status 200
    And match response ==
    """
    {
      schemas: '#array',
      id: '#string',
      userName: '#string',
      name: '#object',
      displayName: '#string',
      active: '#boolean',
      emails: '#array',
      groups: '#array',
      meta: '#object'
    }
    """
    And match response.schemas contains 'urn:ietf:params:scim:schemas:core:2.0:User'
    And match response.id == '#string'
    And match response.userName == '#string'
    And match response.name ==
    """
    {
      givenName: '#string',
      familyName: '#string'
    }
    """
    And match response.displayName == '#string'
    And match response.active == '#boolean'
    And match response.emails contains
    """
    {
      value: '#string',
      display: '#string',
      primary: '#boolean'
    }
    """
    And match response.groups contains
    """
    {
      value: '#string',
      display: '#string'
    }
    """
    And match response.meta ==
    """
    {
      resourceType: '#string',
      location: '#string',
      created: '#string',
      lastModified: '#string'
    }
    """
    And match response.meta.resourceType == 'User'
    And match response.meta.location contains '/v2/scim/2.0/Users/<id>'
    And match response.meta.created == '#string'
    And match response.meta.lastModified == '#string'

    Examples:
      | id                                      |
      | 'd80f7c79-7730-49d8-9a41-7c42fb622d9c'  |

  Scenario Outline: Get a user with invalid ID
    Given path '/v2/scim/2.0/Users/<id>'
    When method get
    Then status 404
    And match response ==
    """
    {
      status: '#string',
      schemas: '#array',
      detail: '#string'
    }
    """
    And match response.status == '404'
    And match response.schemas contains 'urn:ietf:params:scim:api:messages:2.0:Error'
    And match response.detail == '#string'

    Examples:
      | id                                      |
      | 'invalid-id'                             |

  Scenario: Get a user without authorization
    Given path '/v2/scim/2.0/Users/d80f7c79-7730-49d8-9a41-7c42fb622d9c'
    When method get
    Then status 401
    And match response ==
    """
    {
      status: '#string',
      schemas: '#array',
      detail: '#string'
    }
    """
    And match response.status == '401'
    And match response.schemas contains 'urn:ietf:params:scim:api:messages:2.0:Error'
    And match response.detail == '#string'
