# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/scim/2.0/ResourceTypes/{name}_get for http method type GET 
# RoostTestHash=91596feea5
# 
# 

# ********RoostGPT********
Feature: Get a resource type

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Get a resource type with valid name
    Given path '/v2/scim/2.0/ResourceTypes/<name>'
    When method get
    Then status 200
    And match response ==
    """
    {
      schemas: '#? _ == null || typeof _ == "array"',
      id: '#? _ == null || typeof _ == "string"',
      name: '#? _ == null || typeof _ == "string"',
      description: '#? _ == null || typeof _ == "string"',
      endpoint: '#? _ == null || typeof _ == "string"',
      schema: '#? _ == null || typeof _ == "string"'
    }
    """
    And match response.schemas contains 'urn:ietf:params:scim:schemas:core:2.0:ResourceType'
    And match response.id == '<name>'
    And match response.name == '<name>'
    And match response.description == '<name>'
    And match response.endpoint == '/Users'
    And match response.schema == 'urn:ietf:params:scim:schemas:core:2.0:User'

    Examples:
      | name  |
      | 'User' |

  Scenario: Get a resource type with invalid name
    Given path '/v2/scim/2.0/ResourceTypes/InvalidName'
    When method get
    Then status 404
    And match response ==
    """
    {
      status: '404',
      schemas: '#? _ == null || typeof _ == "array"',
      detail: '#? _ == null || typeof _ == "string"'
    }
    """
    And match response.schemas contains 'urn:ietf:params:scim:api:messages:2.0:Error'

  Scenario: Get a resource type with no authorization
    Given path '/v2/scim/2.0/ResourceTypes/User'
    And configure headers = { Accept: 'application/json' }
    When method get
    Then status 401
    And match response ==
    """
    {
      status: '401',
      schemas: '#? _ == null || typeof _ == "array"',
      detail: '#? _ == null || typeof _ == "string"'
    }
    """
    And match response.schemas contains 'urn:ietf:params:scim:api:messages:2.0:Error'

  Scenario: Get a resource type with internal server error
    Given path '/v2/scim/2.0/ResourceTypes/User'
    When method get
    Then status 500
    And match response ==
    """
    {
      status: '500',
      schemas: '#? _ == null || typeof _ == "array"',
      detail: '#? _ == null || typeof _ == "string"'
    }
    """
    And match response.schemas contains 'urn:ietf:params:scim:api:messages:2.0:Error'
