# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/scim/2.0/Schemas/{id}_get for http method type GET 
# RoostTestHash=25e22b4df7
# 
# 

# ********RoostGPT********
Feature: Get a schema

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Get a schema with valid id
    Given path '/v2/scim/2.0/Schemas/<id>'
    When method get
    Then status 200
    And match response ==
    """
    {
      schemas: '#[]',
      id: '#string',
      name: '#string',
      description: '#string',
      attributes: '#[]'
    }
    """
    And match response.schemas == '#[]'
    And match response.id == '#string'
    And match response.name == '#string'
    And match response.description == '#string'
    And match response.attributes == '#[]'
    And match each response.attributes[*].name == '#string'
    And match each response.attributes[*].type == '#string'
    And match each response.attributes[*].multiValued == '#boolean'
    And match each response.attributes[*].description == '#string'
    And match each response.attributes[*].required == '#boolean'
    And match each response.attributes[*].caseExact == '#boolean'
    And match each response.attributes[*].mutability == '#string'
    And match each response.attributes[*].returned == '#string'
    And match each response.attributes[*].uniqueness == '#string'
    And match each response.attributes[*].subAttributes == '#[]'
    And match each response.attributes[*].subAttributes[*].name == '#string'
    And match each response.attributes[*].subAttributes[*].type == '#string'
    And match each response.attributes[*].subAttributes[*].multiValued == '#boolean'
    And match each response.attributes[*].subAttributes[*].description == '#string'
    And match each response.attributes[*].subAttributes[*].required == '#boolean'
    And match each response.attributes[*].subAttributes[*].caseExact == '#boolean'
    And match each response.attributes[*].subAttributes[*].mutability == '#string'
    And match each response.attributes[*].subAttributes[*].returned == '#string'
    And match each response.attributes[*].subAttributes[*].uniqueness == '#string'

    Examples:
      | id                                      |
      | 'urn:ietf:params:scim:schemas:core:2.0:User' |

  Scenario Outline: Get a schema with invalid id
    Given path '/v2/scim/2.0/Schemas/<id>'
    When method get
    Then status 404
    And match response ==
    """
    {
      status: '#string',
      schemas: '#[]',
      detail: '#string'
    }
    """
    And match response.status == '404'
    And match response.schemas == '#[]'
    And match response.detail == '#string'

    Examples:
      | id                                      |
      | 'invalid_id'                            |

  Scenario: Get a schema without authorization
    Given path '/v2/scim/2.0/Schemas/urn:ietf:params:scim:schemas:core:2.0:User'
    And configure headers = { Accept: 'application/json' }
    When method get
    Then status 401
    And match response ==
    """
    {
      status: '#string',
      schemas: '#[]',
      detail: '#string'
    }
    """
    And match response.status == '401'
    And match response.schemas == '#[]'
    And match response.detail == '#string'
