# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/scim/2.0/Users_post for http method type POST 
# RoostTestHash=02d2e44cbe
# 
# 

# ********RoostGPT********
Feature: Create User

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario Outline: Create User with valid payload
    Given path '/v2/scim/2.0/Users'
    And request
    """
    {
        "schemas": <schemas>,
        "userName": <userName>,
        "name": {
            "givenName": <givenName>,
            "familyName": <familyName>
        }
    }
    """
    When method POST
    Then status 201
    And match response ==
    """
    {
        "schemas": '#? _ == null || typeof _ == "array"',
        "id": '#string',
        "userName": <userName>,
        "name": {
            "givenName": <givenName>,
            "familyName": <familyName>
        },
        "displayName": '#string',
        "active": '#boolean',
        "emails": '#? _ == null || typeof _ == "array"',
        "groups": '#? _ == null || typeof _ == "array"',
        "meta": {
            "resourceType": '#string',
            "location": '#string',
            "created": '#string',
            "lastModified": '#string'
        }
    }
    """
    And match response.meta.location contains '/v2/scim/2.0/Users/'
    And match response.meta.resourceType == 'User'
    And match response.meta.created == '#string'
    And match response.meta.lastModified == '#string'
    And match response.emails[*].value == '#string'
    And match response.emails[*].display == '#string'
    And match response.emails[*].primary == '#boolean'
    And match response.groups[*].value == '#string'
    And match response.groups[*].display == '#string'

    Examples:
    | schemas | userName | givenName | familyName |
    | ['urn:ietf:params:scim:schemas:core:2.0:User'] | 'jon.snow@docker.com' | 'Jon' | 'Snow' |

Scenario: Create User with missing required fields
    Given path '/v2/scim/2.0/Users'
    And request
    """
    {
        "schemas": []
    }
    """
    When method POST
    Then status 400
    And match response ==
    """
    {
        "status": '400',
        "schemas": ['urn:ietf:params:scim:api:messages:2.0:Error'],
        "detail": '#string'
    }
    """

Scenario: Create User with invalid payload
    Given path '/v2/scim/2.0/Users'
    And request
    """
    {
        "schemas": ['urn:ietf:params:scim:schemas:core:2.0:User'],
        "userName": 'invalid-email'
    }
    """
    When method POST
    Then status 400
    And match response ==
    """
    {
        "status": '400',
        "schemas": ['urn:ietf:params:scim:api:messages:2.0:Error'],
        "detail": '#string'
    }
    """

Scenario: Create User with unauthorized access
    Given path '/v2/scim/2.0/Users'
    And request
    """
    {
        "schemas": ['urn:ietf:params:scim:schemas:core:2.0:User'],
        "userName": 'jon.snow@docker.com'
    }
    """
    And configure headers = { Authorization: 'Bearer invalid_token' }
    When method POST
    Then status 401
    And match response ==
    """
    {
        "status": '401',
        "schemas": ['urn:ietf:params:scim:api:messages:2.0:Error'],
        "detail": '#string'
    }
    """

Scenario: Create User with forbidden access
    Given path '/v2/scim/2.0/Users'
    And request
    """
    {
        "schemas": ['urn:ietf:params:scim:schemas:core:2.0:User'],
        "userName": 'jon.snow@docker.com'
    }
    """
    When method POST
    Then status 403
    And match response ==
    """
    {
        "status": '403',
        "schemas": ['urn:ietf:params:scim:api:messages:2.0:Error'],
        "detail": '#string'
    }
    """

Scenario: Create User with conflict
    Given path '/v2/scim/2.0/Users'
    And request
    """
    {
        "schemas": ['urn:ietf:params:scim:schemas:core:2.0:User'],
        "userName": 'jon.snow@docker.com'
    }
    """
    When method POST
    Then status 409
    And match response ==
    """
    {
        "status": '409',
        "schemas": ['urn:ietf:params:scim:api:messages:2.0:Error'],
        "detail": '#string'
    }
    """

Scenario: Create User with internal error
    Given path '/v2/scim/2.0/Users'
    And request
    """
    {
        "schemas": ['urn:ietf:params:scim:schemas:core:2.0:User'],
        "userName": 'jon.snow@docker.com'
    }
    """
    When method POST
    Then status 500
    And match response ==
    """
    {
        "status": '500',
        "schemas": ['urn:ietf:params:scim:api:messages:2.0:Error'],
        "detail": '#string'
    }
    """
