# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/scim/2.0/ResourceTypes_get for http method type GET 
# RoostTestHash=f9ea173383
# 
# 

# ********RoostGPT********
Feature: List resource types

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario: List resource types with valid authorization
    Given path '/v2/scim/2.0/ResourceTypes'
    When method get
    Then status 200
    And match response ==
    """
    {
      "schemas": "#? _ == null || typeof _ == 'array'",
      "totalResults": "#? _ == null || typeof _ == 'number'",
      "resources": "#? _ == null || typeof _ == 'array'"
    }
    """
    And match response.schemas == '#? _ == null || typeof _ == "array"'
    And match response.totalResults == '#? _ == null || typeof _ == "number"'
    And match response.resources == '#? _ == null || typeof _ == "array"'
    And match response.resources[*].schemas == '#? _ == null || typeof _ == "array"'
    And match response.resources[*].id == '#? _ == null || typeof _ == "string"'
    And match response.resources[*].name == '#? _ == null || typeof _ == "string"'
    And match response.resources[*].description == '#? _ == null || typeof _ == "string"'
    And match response.resources[*].endpoint == '#? _ == null || typeof _ == "string"'
    And match response.resources[*].schema == '#? _ == null || typeof _ == "string"'
    And match response.resources[*].schemas[*].contains('urn:ietf:params:scim:schemas:core:2.0:ResourceType')
    And match response.resources[*].id.contains('User')
    And match response.resources[*].name.contains('User')
    And match response.resources[*].description.contains('User')
    And match response.resources[*].endpoint.contains('/Users')
    And match response.resources[*].schema.contains('urn:ietf:params:scim:schemas:core:2.0:User')

  Scenario: List resource types with invalid authorization
    Given path '/v2/scim/2.0/ResourceTypes'
    And configure headers = { Authorization: 'Bearer invalid_token', Accept: 'application/json' }
    When method get
    Then status 401
    And match response ==
    """
    {
      "status": "#? _ == null || typeof _ == 'string'",
      "schemas": "#? _ == null || typeof _ == 'array'",
      "detail": "#? _ == null || typeof _ == 'string'"
    }
    """
    And match response.status == '#? _ == null || typeof _ == "string"'
    And match response.schemas == '#? _ == null || typeof _ == "array"'
    And match response.detail == '#? _ == null || typeof _ == "string"'
    And match response.schemas[*].contains('urn:ietf:params:scim:api:messages:2.0:Error')
    And match response.status.contains('401')

  Scenario: List resource types with internal error
    Given path '/v2/scim/2.0/ResourceTypes'
    When method get
    Then status 500
    And match response ==
    """
    {
      "status": "#? _ == null || typeof _ == 'string'",
      "schemas": "#? _ == null || typeof _ == 'array'",
      "detail": "#? _ == null || typeof _ == 'string'"
    }
    """
    And match response.status == '#? _ == null || typeof _ == "string"'
    And match response.schemas == '#? _ == null || typeof _ == "array"'
    And match response.detail == '#? _ == null || typeof _ == "string"'
    And match response.schemas[*].contains('urn:ietf:params:scim:api:messages:2.0:Error')
    And match response.status.contains('500')
