# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/scim/2.0/ServiceProviderConfig_get for http method type GET 
# RoostTestHash=c85e473229
# 
# 

# ********RoostGPT********
Feature: Get Service Provider Config

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario: Get Service Provider Config Success
    Given path '/v2/scim/2.0/ServiceProviderConfig'
    When method GET
    Then status 200
    And match response ==
    """
    {
      schemas: '#? _ == null || typeof _ == "array"',
      documentationUri: '#? _ == null || typeof _ == "string"',
      patch: {
        supported: '#? _ == null || typeof _ == "boolean"'
      },
      bulk: {
        supported: '#? _ == null || typeof _ == "boolean"',
        maxOperations: '#? _ == null || typeof _ == "number"',
        maxPayloadSize: '#? _ == null || typeof _ == "number"'
      },
      filter: {
        supported: '#? _ == null || typeof _ == "boolean"',
        maxResults: '#? _ == null || typeof _ == "number"'
      },
      changePassword: {
        supported: '#? _ == null || typeof _ == "boolean"'
      },
      sort: {
        supported: '#? _ == null || typeof _ == "boolean"'
      },
      etag: {
        supported: '#? _ == null || typeof _ == "boolean"'
      },
      authenticationSchemes: {
        name: '#? _ == null || typeof _ == "string"',
        description: '#? _ == null || typeof _ == "string"',
        specUri: '#? _ == null || typeof _ == "string"',
        type: '#? _ == null || typeof _ == "string"'
      }
    }
    """

  Scenario: Get Service Provider Config Unauthorized
    Given path '/v2/scim/2.0/ServiceProviderConfig'
    When method GET
    Then status 401
    And match response ==
    """
    {
      status: '#? _ == null || typeof _ == "string"',
      schemas: '#? _ == null || typeof _ == "array"',
      detail: '#? _ == null || typeof _ == "string"'
    }
    """

  Scenario: Get Service Provider Config Internal Error
    Given path '/v2/scim/2.0/ServiceProviderConfig'
    When method GET
    Then status 500
    And match response ==
    """
    {
      status: '#? _ == null || typeof _ == "string"',
      schemas: '#? _ == null || typeof _ == "array"',
      detail: '#? _ == null || typeof _ == "string"'
    }
    """
