# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/scim/2.0/Schemas_get for http method type GET 
# RoostTestHash=f86bf412b5
# 
# 

# ********RoostGPT********
Feature: List SCIM Schemas

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }

Scenario: List schemas with valid authorization
    Given path '/v2/scim/2.0/Schemas'
    When method get
    Then status 200
    And match response ==
    """
    {
        schemas: '#array',
        totalResults: '#number',
        resources: '#array'
    }
    """
    And match response.schemas == '#array'
    And match response.totalResults == '#number'
    And match response.resources == '#array'
    And match each response.resources[*].schemas == '#array'
    And match each response.resources[*].schemas[*].type == '#string'
    And match each response.resources[*].id == '#string'
    And match each response.resources[*].name == '#string'
    And match each response.resources[*].description == '#string'
    And match each response.resources[*].attributes == '#array'
    And match each response.resources[*].attributes[*].name == '#string'
    And match each response.resources[*].attributes[*].type == '#string'
    And match each response.resources[*].attributes[*].multiValued == '#boolean'
    And match each response.resources[*].attributes[*].description == '#string'
    And match each response.resources[*].attributes[*].required == '#boolean'
    And match each response.resources[*].attributes[*].caseExact == '#boolean'
    And match each response.resources[*].attributes[*].mutability == '#string'
    And match each response.resources[*].attributes[*].returned == '#string'
    And match each response.resources[*].attributes[*].uniqueness == '#string'
    And match each response.resources[*].attributes[*].subAttributes == '#array'
    And match each response.resources[*].attributes[*].subAttributes[*].name == '#string'
    And match each response.resources[*].attributes[*].subAttributes[*].type == '#string'
    And match each response.resources[*].attributes[*].subAttributes[*].multiValued == '#boolean'
    And match each response.resources[*].attributes[*].subAttributes[*].description == '#string'
    And match each response.resources[*].attributes[*].subAttributes[*].required == '#boolean'
    And match each response.resources[*].attributes[*].subAttributes[*].caseExact == '#boolean'
    And match each response.resources[*].attributes[*].subAttributes[*].mutability == '#string'
    And match each response.resources[*].attributes[*].subAttributes[*].returned == '#string'
    And match each response.resources[*].attributes[*].subAttributes[*].uniqueness == '#string'

Scenario: List schemas with invalid authorization
    Given path '/v2/scim/2.0/Schemas'
    And configure headers = { Authorization: 'Bearer invalid_token' }
    When method get
    Then status 401
    And match response ==
    """
    {
        status: '401',
        schemas: '#array',
        detail: '#string'
    }
    """
    And match response.status == '401'
    And match response.schemas == '#array'
    And match response.detail == '#string'

Scenario: List schemas with internal error
    Given path '/v2/scim/2.0/Schemas'
    When method get
    Then status 500
    And match response ==
    """
    {
        status: '500',
        schemas: '#array',
        detail: '#string'
    }
    """
    And match response.status == '500'
    And match response.schemas == '#array'
    And match response.detail == '#string'
