# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/scim/2.0/Users/{id}_put for http method type PUT 
# RoostTestHash=a048f427cd
# 
# 

# ********RoostGPT********
Feature: Update a user

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }

Scenario Outline: Update a user with valid payload
    Given path '/v2/scim/2.0/Users/<id>'
    And request
    """
    {
        "schemas": <schemas>,
        "name": <name>,
        "enabled": <enabled>
    }
    """
    When method PUT
    Then status <status>
    And match response ==
    """
    {
        "schemas": '#array',
        "id": '#string',
        "userName": '#string',
        "name": {
            "givenName": '#string',
            "familyName": '#string'
        },
        "displayName": '#string',
        "active": '#boolean',
        "emails": '#array',
        "groups": '#array',
        "meta": {
            "resourceType": '#string',
            "location": '#string',
            "created": '#string',
            "lastModified": '#string'
        }
    }
    """
    Examples:
        | id                     | schemas                        | name                                                                 | enabled | status |
        | 'd80f7c79-7730-49d8-9a41-7c42fb622d9c' | ['urn:ietf:params:scim:schemas:core:2.0:User'] | { "givenName": 'Jon', "familyName": 'Snow' } | true    | 200    |
        | 'd80f7c79-7730-49d8-9a41-7c42fb622d9c' | ['urn:ietf:params:scim:schemas:core:2.0:User'] | { "givenName": 'Jon', "familyName": 'Snow' } | false   | 200    |

Scenario Outline: Update a user with invalid payload
    Given path '/v2/scim/2.0/Users/<id>'
    And request
    """
    {
        "schemas": <schemas>,
        "name": <name>,
        "enabled": <enabled>
    }
    """
    When method PUT
    Then status <status>
    And match response ==
    """
    {
        "status": '#string',
        "schemas": '#array',
        "detail": '#string',
        "scimType": '#string'
    }
    """
    Examples:
        | id                     | schemas                        | name                                                                 | enabled | status |
        | 'd80f7c79-7730-49d8-9a41-7c42fb622d9c' | ['urn:ietf:params:scim:schemas:core:2.0:User'] | { "givenName": 'Jon', "familyName": 'Snow' } | 'invalid' | 400    |
        | 'd80f7c79-7730-49d8-9a41-7c42fb622d9c' | ['urn:ietf:params:scim:schemas:core:2.0:User'] | { "givenName": 'Jon', "familyName": 'Snow' } | 'invalid' | 401    |
        | 'd80f7c79-7730-49d8-9a41-7c42fb622d9c' | ['urn:ietf:params:scim:schemas:core:2.0:User'] | { "givenName": 'Jon', "familyName": 'Snow' } | 'invalid' | 403    |
        | 'd80f7c79-7730-49d8-9a41-7c42fb622d9c' | ['urn:ietf:params:scim:schemas:core:2.0:User'] | { "givenName": 'Jon', "familyName": 'Snow' } | 'invalid' | 404    |
        | 'd80f7c79-7730-49d8-9a41-7c42fb622d9c' | ['urn:ietf:params:scim:schemas:core:2.0:User'] | { "givenName": 'Jon', "familyName": 'Snow' } | 'invalid' | 409    |
        | 'd80f7c79-7730-49d8-9a41-7c42fb622d9c' | ['urn:ietf:params:scim:schemas:core:2.0:User'] | { "givenName": 'Jon', "familyName": 'Snow' } | 'invalid' | 500    |
