# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/scim/2.0/Users_get for http method type GET 
# RoostTestHash=6d09b880f6
# 
# 

# ********RoostGPT********
Feature: List users

  Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = Bearer +  karate.properties['AUTH_TOKEN'] || karate.properties['BEARER_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: List users with valid parameters
    Given path '/v2/scim/2.0/Users'
    And param startIndex = <startIndex>
    And param count = <count>
    And param filter = <filter>
    And param attributes = <attributes>
    And param sortOrder = <sortOrder>
    And param sortBy = <sortBy>
    When method get
    Then status 200
    And match response ==
    """
    {
      schemas: '#? _ == null || typeof _ == "array"',
      totalResults: '#? _ == null || typeof _ == "number"',
      startIndex: '#? _ == null || typeof _ == "number"',
      itemsPerPage: '#? _ == null || typeof _ == "number"',
      resources: '#? _ == null || typeof _ == "array"'
    }
    """
    And match each resources[*].schemas == '#? _ == null || typeof _ == "array"'
    And match each resources[*].id == '#? _ == null || typeof _ == "string"'
    And match each resources[*].userName == '#? _ == null || typeof _ == "string"'
    And match each resources[*].name == '#? _ == null || typeof _ == "object"'
    And match each resources[*].name.givenName == '#? _ == null || typeof _ == "string"'
    And match each resources[*].name.familyName == '#? _ == null || typeof _ == "string"'
    And match each resources[*].displayName == '#? _ == null || typeof _ == "string"'
    And match each resources[*].active == '#? _ == null || typeof _ == "boolean"'
    And match each resources[*].emails == '#? _ == null || typeof _ == "array"'
    And match each resources[*].emails[*].value == '#? _ == null || typeof _ == "string"'
    And match each resources[*].emails[*].display == '#? _ == null || typeof _ == "string"'
    And match each resources[*].emails[*].primary == '#? _ == null || typeof _ == "boolean"'
    And match each resources[*].groups == '#? _ == null || typeof _ == "array"'
    And match each resources[*].groups[*].value == '#? _ == null || typeof _ == "string"'
    And match each resources[*].groups[*].display == '#? _ == null || typeof _ == "string"'
    And match each resources[*].meta == '#? _ == null || typeof _ == "object"'
    And match each resources[*].meta.resourceType == '#? _ == null || typeof _ == "string"'
    And match each resources[*].meta.location == '#? _ == null || typeof _ == "string"'
    And match each resources[*].meta.created == '#? _ == null || typeof _ == "string"'
    And match each resources[*].meta.lastModified == '#? _ == null || typeof _ == "string"'

    Examples:
      | startIndex | count | filter                           | attributes         | sortOrder | sortBy   |
      | 1          | 10    | 'userName eq "jon.snow@docker.com"' | 'userName,displayName' | 'ascending' | 'userName' |
      | 2          | 20    | 'userName eq "daenerys@docker.com"' | 'userName,displayName' | 'descending' | 'userName' |

  Scenario Outline: List users with invalid parameters
    Given path '/v2/scim/2.0/Users'
    And param startIndex = <startIndex>
    And param count = <count>
    And param filter = <filter>
    And param attributes = <attributes>
    And param sortOrder = <sortOrder>
    And param sortBy = <sortBy>
    When method get
    Then status <expectedStatus>
    And match response ==
    """
    {
      status: '#? _ == null || typeof _ == "string"',
      schemas: '#? _ == null || typeof _ == "array"',
      detail: '#? _ == null || typeof _ == "string"'
    }
    """

    Examples:
      | startIndex | count | filter | attributes | sortOrder | sortBy | expectedStatus |
      | -1         | 10    | ''      | ''         | ''        | ''      | 400             |
      | 1          | -1    | ''      | ''         | ''        | ''      | 400             |
      | 1          | 10    | ''      | ''         | ''        | ''      | 400             |
      | 1          | 10    | ''      | ''         | ''        | ''      | 400             |

  Scenario: List users without authorization
    Given path '/v2/scim/2.0/Users'
    And param startIndex = 1
    And param count = 10
    When method get
    Then status 401
    And match response ==
    """
    {
      status: '#? _ == null || typeof _ == "string"',
      schemas: '#? _ == null || typeof _ == "array"',
      detail: '#? _ == null || typeof _ == "string"'
    }
    """
