# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/users/2fa-login_post for http method type POST 
# RoostTestHash=8888bd2a20
# 
# 

# ********RoostGPT********
Feature: Second Factor Authentication

Background:
    * def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }

Scenario Outline: Test POST /v2/users/2fa-login with valid input
    Given path '/v2/users/2fa-login'
    And request
    """
    {
        "login_2fa_token": '<login_2fa_token>',
        "code": '<code>'
    }
    """
    When method post
    Then status <status>
    And match response ==
    """
    {
        token: '#string'
    }
    """
    Examples:
    | login_2fa_token                                                                 | code   | status |
    | 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c' | 123456 | 200    |

Scenario Outline: Test POST /v2/users/2fa-login with invalid input
    Given path '/v2/users/2fa-login'
    And request
    """
    {
        "login_2fa_token": '<login_2fa_token>',
        "code": '<code>'
    }
    """
    When method post
    Then status <status>
    And match response ==
    """
    {
        detail: '#string'
    }
    """
    Examples:
    | login_2fa_token                                                                 | code   | status |
    | 'invalid_token'                                                                 | 123456 | 401    |
    | 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c' | 654321 | 401    |
