# ********RoostGPT********

# Test generated by RoostGPT for test api-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /v2/users/login_post for http method type POST 
# RoostTestHash=a031fa1654
# 
# 

# ********RoostGPT********
Feature: Create an authentication token

Background:
* def baseURL = karate.properties['DOCKER_HUB_API_BASE_URL'] || karate.properties['API_HOST']
* url baseURL
* configure headers = { Accept: 'application/json' }

Scenario Outline: Test successful user login
Given path '/v2/users/login'
And request
"""
{
  "username": '<username>',
  "password": '<password>'
}
"""
When method post
Then status 200
And match response.token == '#string'
And match response.token contains 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9'

Examples:
| username | password |
| 'myusername' | 'p@ssw0rd' |

Scenario Outline: Test authentication failed or second factor required
Given path '/v2/users/login'
And request
"""
{
  "username": '<username>',
  "password": '<password>'
}
"""
When method post
Then status 401
And match response.detail == '#string'
And match response.detail contains 'Incorrect authentication credentials'
And match response.login_2fa_token == '##string'

Examples:
| username | password |
| 'wrongusername' | 'wrongpassword' |
